# frozen_string_literal: true

require "bundler/gem_tasks"
require "rake/testtask"
require "standard/rake"

Rake::TestTask.new(:test) do |t|
  t.libs << "lib"
  t.libs << "spec"
  t.test_files = FileList["spec/**/*_spec.rb"]
  t.warning = false
end

task default: [:"standard:fix", :test]
