// Code generated by scripts/generate_conformance_dispatch.rb from spec/operations.json. DO NOT EDIT.
package conformance

import (
	"context"
	"testing"

	wenmar "github.com/wenmar-pro/wenmar-sdk/go/wenmar"
)

type operationFunc func(ctx context.Context, t *testing.T, client *wenmar.Client, args map[string]interface{}) (interface{}, error)

var dispatch = map[string]operationFunc{
"list_account": func(ctx context.Context, t *testing.T, c *wenmar.Client, args map[string]interface{}) (interface{}, error) {
	resp, err := c.ListAccount(ctx)
	if err != nil {
		return nil, err
	}
	return decodeBody(resp.Body)
},

"list_customer_tags": func(ctx context.Context, t *testing.T, c *wenmar.Client, args map[string]interface{}) (interface{}, error) {
	resp, err := c.ListCustomerTags(ctx)
	if err != nil {
		return nil, err
	}
	return decodeBody(resp.Body)
},

"create_customer_tag": func(ctx context.Context, t *testing.T, c *wenmar.Client, args map[string]interface{}) (interface{}, error) {
	resp, err := c.CreateCustomerTag(ctx, buildWrapper[CreateCustomerTagRequest]("name", args["requestBody"]))
	if err != nil {
		return nil, err
	}
	return decodeBody(resp.Body)
},

"delete_customer_tag": func(ctx context.Context, t *testing.T, c *wenmar.Client, args map[string]interface{}) (interface{}, error) {
	resp, err := c.DeleteCustomerTag(ctx, intArg(args["pathParams"], "id"))
	if err != nil {
		return nil, err
	}
	return decodeBody(resp.Body)
},

"update_customer_tag": func(ctx context.Context, t *testing.T, c *wenmar.Client, args map[string]interface{}) (interface{}, error) {
	resp, err := c.UpdateCustomerTag(ctx, intArg(args["pathParams"], "id"), buildWrapper[UpdateCustomerTagRequest]("name", args["requestBody"]))
	if err != nil {
		return nil, err
	}
	return decodeBody(resp.Body)
},

"list_customers": func(ctx context.Context, t *testing.T, c *wenmar.Client, args map[string]interface{}) (interface{}, error) {
	resp, err := c.ListCustomers(ctx, &ListCustomersParams{HasBalance: ptrVal(args["query"], "has_balance"), HasVehicle: ptrVal(args["query"], "has_vehicle"), LastVisitMonths: ptrVal(args["query"], "last_visit_months"), Page: ptrVal(args["query"], "page"), PerPage: ptrVal(args["query"], "per_page"), Query: ptrVal(args["query"], "query"), TagIds: ptrVal(args["query"], "tag_ids"), Type: ptrVal(args["query"], "type")})
	if err != nil {
		return nil, err
	}
	return decodeBody(resp.Body)
},

"create_customer": func(ctx context.Context, t *testing.T, c *wenmar.Client, args map[string]interface{}) (interface{}, error) {
	resp, err := c.CreateCustomer(ctx, buildWrapper[CreateCustomerRequest]("customer", args["requestBody"]))
	if err != nil {
		return nil, err
	}
	return decodeBody(resp.Body)
},

"check_customer_duplicate": func(ctx context.Context, t *testing.T, c *wenmar.Client, args map[string]interface{}) (interface{}, error) {
	resp, err := c.CheckCustomerDuplicate(ctx, &CheckCustomerDuplicateParams{Email: ptrVal(args["query"], "email"), FirstName: ptrVal(args["query"], "first_name"), LastName: ptrVal(args["query"], "last_name"), Phone: ptrVal(args["query"], "phone")})
	if err != nil {
		return nil, err
	}
	return decodeBody(resp.Body)
},

"lookup_customer": func(ctx context.Context, t *testing.T, c *wenmar.Client, args map[string]interface{}) (interface{}, error) {
	resp, err := c.LookupCustomer(ctx, &LookupCustomerParams{Id: ptrVal(args["query"], "id"), Query: ptrVal(args["query"], "query")})
	if err != nil {
		return nil, err
	}
	return decodeBody(resp.Body)
},

"list_customers_drivers": func(ctx context.Context, t *testing.T, c *wenmar.Client, args map[string]interface{}) (interface{}, error) {
	resp, err := c.ListCustomersDrivers(ctx, intArg(args["pathParams"], "customer_id"))
	if err != nil {
		return nil, err
	}
	return decodeBody(resp.Body)
},

"create_driver": func(ctx context.Context, t *testing.T, c *wenmar.Client, args map[string]interface{}) (interface{}, error) {
	resp, err := c.CreateDriver(ctx, intArg(args["pathParams"], "customer_id"), buildWrapper[CreateDriverRequest]("driver", args["requestBody"]))
	if err != nil {
		return nil, err
	}
	return decodeBody(resp.Body)
},

"delete_driver": func(ctx context.Context, t *testing.T, c *wenmar.Client, args map[string]interface{}) (interface{}, error) {
	resp, err := c.DeleteDriver(ctx, intArg(args["pathParams"], "customer_id"), intArg(args["pathParams"], "id"))
	if err != nil {
		return nil, err
	}
	return decodeBody(resp.Body)
},

"show_driver": func(ctx context.Context, t *testing.T, c *wenmar.Client, args map[string]interface{}) (interface{}, error) {
	resp, err := c.ShowDriver(ctx, intArg(args["pathParams"], "customer_id"), intArg(args["pathParams"], "id"))
	if err != nil {
		return nil, err
	}
	return decodeBody(resp.Body)
},

"update_driver": func(ctx context.Context, t *testing.T, c *wenmar.Client, args map[string]interface{}) (interface{}, error) {
	resp, err := c.UpdateDriver(ctx, intArg(args["pathParams"], "customer_id"), intArg(args["pathParams"], "id"), buildWrapper[UpdateDriverRequest]("driver", args["requestBody"]))
	if err != nil {
		return nil, err
	}
	return decodeBody(resp.Body)
},

"list_customers_statements": func(ctx context.Context, t *testing.T, c *wenmar.Client, args map[string]interface{}) (interface{}, error) {
	resp, err := c.ListCustomersStatements(ctx, intArg(args["pathParams"], "customer_id"))
	if err != nil {
		return nil, err
	}
	return decodeBody(resp.Body)
},

"list_customers_vehicles": func(ctx context.Context, t *testing.T, c *wenmar.Client, args map[string]interface{}) (interface{}, error) {
	resp, err := c.ListCustomersVehicles(ctx, intArg(args["pathParams"], "customer_id"))
	if err != nil {
		return nil, err
	}
	return decodeBody(resp.Body)
},

"get_customers_vehicle_history": func(ctx context.Context, t *testing.T, c *wenmar.Client, args map[string]interface{}) (interface{}, error) {
	resp, err := c.GetCustomersVehicleHistory(ctx, intArg(args["pathParams"], "customer_id"), intArg(args["pathParams"], "vehicle_id"))
	if err != nil {
		return nil, err
	}
	return decodeBody(resp.Body)
},

"list_customers_work_orders": func(ctx context.Context, t *testing.T, c *wenmar.Client, args map[string]interface{}) (interface{}, error) {
	resp, err := c.ListCustomersWorkOrders(ctx, intArg(args["pathParams"], "customer_id"))
	if err != nil {
		return nil, err
	}
	return decodeBody(resp.Body)
},

"delete_customer": func(ctx context.Context, t *testing.T, c *wenmar.Client, args map[string]interface{}) (interface{}, error) {
	resp, err := c.DeleteCustomer(ctx, intArg(args["pathParams"], "id"))
	if err != nil {
		return nil, err
	}
	return decodeBody(resp.Body)
},

"show_customer": func(ctx context.Context, t *testing.T, c *wenmar.Client, args map[string]interface{}) (interface{}, error) {
	resp, err := c.ShowCustomer(ctx, intArg(args["pathParams"], "id"))
	if err != nil {
		return nil, err
	}
	return decodeBody(resp.Body)
},

"update_customer": func(ctx context.Context, t *testing.T, c *wenmar.Client, args map[string]interface{}) (interface{}, error) {
	resp, err := c.UpdateCustomer(ctx, intArg(args["pathParams"], "id"), buildWrapper[UpdateCustomerRequest]("customer", args["requestBody"]))
	if err != nil {
		return nil, err
	}
	return decodeBody(resp.Body)
},

"merge_customer": func(ctx context.Context, t *testing.T, c *wenmar.Client, args map[string]interface{}) (interface{}, error) {
	resp, err := c.MergeCustomer(ctx, intArg(args["pathParams"], "id"), buildWrapper[MergeCustomerRequest]("source_customer_id", args["requestBody"]))
	if err != nil {
		return nil, err
	}
	return decodeBody(resp.Body)
},

"show_location": func(ctx context.Context, t *testing.T, c *wenmar.Client, args map[string]interface{}) (interface{}, error) {
	resp, err := c.ShowLocation(ctx, intArg(args["pathParams"], "id"))
	if err != nil {
		return nil, err
	}
	return decodeBody(resp.Body)
},

"list_service_categories": func(ctx context.Context, t *testing.T, c *wenmar.Client, args map[string]interface{}) (interface{}, error) {
	resp, err := c.ListServiceCategories(ctx)
	if err != nil {
		return nil, err
	}
	return decodeBody(resp.Body)
},

"create_service_category": func(ctx context.Context, t *testing.T, c *wenmar.Client, args map[string]interface{}) (interface{}, error) {
	resp, err := c.CreateServiceCategory(ctx, buildWrapper[CreateServiceCategoryRequest]("service_category", args["requestBody"]))
	if err != nil {
		return nil, err
	}
	return decodeBody(resp.Body)
},

"seed_defaults_service_categories": func(ctx context.Context, t *testing.T, c *wenmar.Client, args map[string]interface{}) (interface{}, error) {
	resp, err := c.SeedDefaultsServiceCategories(ctx, SeedDefaultsServiceCategoriesRequest{})
	if err != nil {
		return nil, err
	}
	return decodeBody(resp.Body)
},

"delete_service_category": func(ctx context.Context, t *testing.T, c *wenmar.Client, args map[string]interface{}) (interface{}, error) {
	resp, err := c.DeleteServiceCategory(ctx, intArg(args["pathParams"], "id"))
	if err != nil {
		return nil, err
	}
	return decodeBody(resp.Body)
},

"update_service_category": func(ctx context.Context, t *testing.T, c *wenmar.Client, args map[string]interface{}) (interface{}, error) {
	resp, err := c.UpdateServiceCategory(ctx, intArg(args["pathParams"], "id"), buildWrapper[UpdateServiceCategoryRequest]("service_category", args["requestBody"]))
	if err != nil {
		return nil, err
	}
	return decodeBody(resp.Body)
},

"deactivate_service_category": func(ctx context.Context, t *testing.T, c *wenmar.Client, args map[string]interface{}) (interface{}, error) {
	resp, err := c.DeactivateServiceCategory(ctx, intArg(args["pathParams"], "id"), DeactivateServiceCategoryRequest{})
	if err != nil {
		return nil, err
	}
	return decodeBody(resp.Body)
},

"move_down_service_category": func(ctx context.Context, t *testing.T, c *wenmar.Client, args map[string]interface{}) (interface{}, error) {
	resp, err := c.MoveDownServiceCategory(ctx, intArg(args["pathParams"], "id"), MoveDownServiceCategoryRequest{})
	if err != nil {
		return nil, err
	}
	return decodeBody(resp.Body)
},

"move_up_service_category": func(ctx context.Context, t *testing.T, c *wenmar.Client, args map[string]interface{}) (interface{}, error) {
	resp, err := c.MoveUpServiceCategory(ctx, intArg(args["pathParams"], "id"), MoveUpServiceCategoryRequest{})
	if err != nil {
		return nil, err
	}
	return decodeBody(resp.Body)
},

"reactivate_service_category": func(ctx context.Context, t *testing.T, c *wenmar.Client, args map[string]interface{}) (interface{}, error) {
	resp, err := c.ReactivateServiceCategory(ctx, intArg(args["pathParams"], "id"), ReactivateServiceCategoryRequest{})
	if err != nil {
		return nil, err
	}
	return decodeBody(resp.Body)
},

"list_tags": func(ctx context.Context, t *testing.T, c *wenmar.Client, args map[string]interface{}) (interface{}, error) {
	resp, err := c.ListTags(ctx)
	if err != nil {
		return nil, err
	}
	return decodeBody(resp.Body)
},

"update_tags": func(ctx context.Context, t *testing.T, c *wenmar.Client, args map[string]interface{}) (interface{}, error) {
	resp, err := c.UpdateTags(ctx, UpdateTagsRequest{})
	if err != nil {
		return nil, err
	}
	return decodeBody(resp.Body)
},

"show_statement": func(ctx context.Context, t *testing.T, c *wenmar.Client, args map[string]interface{}) (interface{}, error) {
	resp, err := c.ShowStatement(ctx, intArg(args["pathParams"], "id"))
	if err != nil {
		return nil, err
	}
	return decodeBody(resp.Body)
},

"list_team": func(ctx context.Context, t *testing.T, c *wenmar.Client, args map[string]interface{}) (interface{}, error) {
	resp, err := c.ListTeam(ctx)
	if err != nil {
		return nil, err
	}
	return decodeBody(resp.Body)
},

"list_vehicle_tags": func(ctx context.Context, t *testing.T, c *wenmar.Client, args map[string]interface{}) (interface{}, error) {
	resp, err := c.ListVehicleTags(ctx)
	if err != nil {
		return nil, err
	}
	return decodeBody(resp.Body)
},

"create_vehicle_tag": func(ctx context.Context, t *testing.T, c *wenmar.Client, args map[string]interface{}) (interface{}, error) {
	resp, err := c.CreateVehicleTag(ctx, buildWrapper[CreateVehicleTagRequest]("name", args["requestBody"]))
	if err != nil {
		return nil, err
	}
	return decodeBody(resp.Body)
},

"delete_vehicle_tag": func(ctx context.Context, t *testing.T, c *wenmar.Client, args map[string]interface{}) (interface{}, error) {
	resp, err := c.DeleteVehicleTag(ctx, intArg(args["pathParams"], "id"))
	if err != nil {
		return nil, err
	}
	return decodeBody(resp.Body)
},

"update_vehicle_tag": func(ctx context.Context, t *testing.T, c *wenmar.Client, args map[string]interface{}) (interface{}, error) {
	resp, err := c.UpdateVehicleTag(ctx, intArg(args["pathParams"], "id"), buildWrapper[UpdateVehicleTagRequest]("name", args["requestBody"]))
	if err != nil {
		return nil, err
	}
	return decodeBody(resp.Body)
},

"list_vehicles": func(ctx context.Context, t *testing.T, c *wenmar.Client, args map[string]interface{}) (interface{}, error) {
	resp, err := c.ListVehicles(ctx, &ListVehiclesParams{CustomerId: ptrVal(args["query"], "customer_id"), Page: ptrVal(args["query"], "page")})
	if err != nil {
		return nil, err
	}
	return decodeBody(resp.Body)
},

"create_vehicle": func(ctx context.Context, t *testing.T, c *wenmar.Client, args map[string]interface{}) (interface{}, error) {
	resp, err := c.CreateVehicle(ctx, buildWrapper[CreateVehicleRequest]("vehicle", args["requestBody"]))
	if err != nil {
		return nil, err
	}
	return decodeBody(resp.Body)
},

"check_vehicle_duplicate": func(ctx context.Context, t *testing.T, c *wenmar.Client, args map[string]interface{}) (interface{}, error) {
	resp, err := c.CheckVehicleDuplicate(ctx, &CheckVehicleDuplicateParams{Vin: ptrVal(args["query"], "vin")})
	if err != nil {
		return nil, err
	}
	return decodeBody(resp.Body)
},

"lookup_vehicle": func(ctx context.Context, t *testing.T, c *wenmar.Client, args map[string]interface{}) (interface{}, error) {
	resp, err := c.LookupVehicle(ctx, &LookupVehicleParams{Query: ptrVal(args["query"], "query")})
	if err != nil {
		return nil, err
	}
	return decodeBody(resp.Body)
},

"prefill_vehicle": func(ctx context.Context, t *testing.T, c *wenmar.Client, args map[string]interface{}) (interface{}, error) {
	resp, err := c.PrefillVehicle(ctx, &PrefillVehicleParams{Make: ptrVal(args["query"], "make"), Model: ptrVal(args["query"], "model"), Vin: ptrVal(args["query"], "vin"), Year: ptrVal(args["query"], "year")})
	if err != nil {
		return nil, err
	}
	return decodeBody(resp.Body)
},

"decode_vin": func(ctx context.Context, t *testing.T, c *wenmar.Client, args map[string]interface{}) (interface{}, error) {
	resp, err := c.DecodeVin(ctx, &DecodeVinParams{Vin: ptrVal(args["query"], "vin")})
	if err != nil {
		return nil, err
	}
	return decodeBody(resp.Body)
},

"delete_vehicle": func(ctx context.Context, t *testing.T, c *wenmar.Client, args map[string]interface{}) (interface{}, error) {
	resp, err := c.DeleteVehicle(ctx, intArg(args["pathParams"], "id"))
	if err != nil {
		return nil, err
	}
	return decodeBody(resp.Body)
},

"show_vehicle": func(ctx context.Context, t *testing.T, c *wenmar.Client, args map[string]interface{}) (interface{}, error) {
	resp, err := c.ShowVehicle(ctx, intArg(args["pathParams"], "id"))
	if err != nil {
		return nil, err
	}
	return decodeBody(resp.Body)
},

"update_vehicle": func(ctx context.Context, t *testing.T, c *wenmar.Client, args map[string]interface{}) (interface{}, error) {
	resp, err := c.UpdateVehicle(ctx, intArg(args["pathParams"], "id"), buildWrapper[UpdateVehicleRequest]("vehicle", args["requestBody"]))
	if err != nil {
		return nil, err
	}
	return decodeBody(resp.Body)
},

"merge_vehicle": func(ctx context.Context, t *testing.T, c *wenmar.Client, args map[string]interface{}) (interface{}, error) {
	resp, err := c.MergeVehicle(ctx, intArg(args["pathParams"], "id"), buildWrapper[MergeVehicleRequest]("source_vehicle_id", args["requestBody"]))
	if err != nil {
		return nil, err
	}
	return decodeBody(resp.Body)
},

"transfer_vehicle": func(ctx context.Context, t *testing.T, c *wenmar.Client, args map[string]interface{}) (interface{}, error) {
	resp, err := c.TransferVehicle(ctx, intArg(args["pathParams"], "id"), TransferVehicleRequest{CustomerId: flatVal(args["requestBody"], "customer_id"), Mode: flatVal(args["requestBody"], "mode")})
	if err != nil {
		return nil, err
	}
	return decodeBody(resp.Body)
},

"list_vehicles_work_orders": func(ctx context.Context, t *testing.T, c *wenmar.Client, args map[string]interface{}) (interface{}, error) {
	resp, err := c.ListVehiclesWorkOrders(ctx, intArg(args["pathParams"], "vehicle_id"))
	if err != nil {
		return nil, err
	}
	return decodeBody(resp.Body)
},

"list_vendors": func(ctx context.Context, t *testing.T, c *wenmar.Client, args map[string]interface{}) (interface{}, error) {
	resp, err := c.ListVendors(ctx)
	if err != nil {
		return nil, err
	}
	return decodeBody(resp.Body)
},

"show_vendor": func(ctx context.Context, t *testing.T, c *wenmar.Client, args map[string]interface{}) (interface{}, error) {
	resp, err := c.ShowVendor(ctx, intArg(args["pathParams"], "id"))
	if err != nil {
		return nil, err
	}
	return decodeBody(resp.Body)
},

"list_work_orders": func(ctx context.Context, t *testing.T, c *wenmar.Client, args map[string]interface{}) (interface{}, error) {
	resp, err := c.ListWorkOrders(ctx)
	if err != nil {
		return nil, err
	}
	return decodeBody(resp.Body)
},

"create_work_order": func(ctx context.Context, t *testing.T, c *wenmar.Client, args map[string]interface{}) (interface{}, error) {
	resp, err := c.CreateWorkOrder(ctx, buildWrapper[CreateWorkOrderRequest]("work_order", args["requestBody"]))
	if err != nil {
		return nil, err
	}
	return decodeBody(resp.Body)
},

"delete_work_order": func(ctx context.Context, t *testing.T, c *wenmar.Client, args map[string]interface{}) (interface{}, error) {
	resp, err := c.DeleteWorkOrder(ctx, intArg(args["pathParams"], "id"))
	if err != nil {
		return nil, err
	}
	return decodeBody(resp.Body)
},

"show_work_order": func(ctx context.Context, t *testing.T, c *wenmar.Client, args map[string]interface{}) (interface{}, error) {
	resp, err := c.ShowWorkOrder(ctx, intArg(args["pathParams"], "id"))
	if err != nil {
		return nil, err
	}
	return decodeBody(resp.Body)
},

"update_work_order": func(ctx context.Context, t *testing.T, c *wenmar.Client, args map[string]interface{}) (interface{}, error) {
	resp, err := c.UpdateWorkOrder(ctx, intArg(args["pathParams"], "id"), buildWrapper[UpdateWorkOrderRequest]("work_order", args["requestBody"]))
	if err != nil {
		return nil, err
	}
	return decodeBody(resp.Body)
},

"show_work_order_declined_services": func(ctx context.Context, t *testing.T, c *wenmar.Client, args map[string]interface{}) (interface{}, error) {
	resp, err := c.ShowWorkOrderDeclinedServices(ctx, intArg(args["pathParams"], "work_order_id"))
	if err != nil {
		return nil, err
	}
	return decodeBody(resp.Body)
},

"show_work_order_service_history": func(ctx context.Context, t *testing.T, c *wenmar.Client, args map[string]interface{}) (interface{}, error) {
	resp, err := c.ShowWorkOrderServiceHistory(ctx, intArg(args["pathParams"], "work_order_id"))
	if err != nil {
		return nil, err
	}
	return decodeBody(resp.Body)
},

"create_work_order_authorization": func(ctx context.Context, t *testing.T, c *wenmar.Client, args map[string]interface{}) (interface{}, error) {
	resp, err := c.CreateWorkOrderAuthorization(ctx, intArg(args["pathParams"], "work_order_id"), CreateWorkOrderAuthorizationRequest{AuthorizationMethod: flatVal(args["requestBody"], "authorization_method"), ServiceIds: flatVal(args["requestBody"], "service_ids"), ServiceDecisions: flatVal(args["requestBody"], "service_decisions")})
	if err != nil {
		return nil, err
	}
	return decodeBody(resp.Body)
},

"update_work_order_authorization_decisions": func(ctx context.Context, t *testing.T, c *wenmar.Client, args map[string]interface{}) (interface{}, error) {
	resp, err := c.UpdateWorkOrderAuthorizationDecisions(ctx, intArg(args["pathParams"], "work_order_id"), buildWrapper[UpdateWorkOrderAuthorizationDecisionsRequest]("service_decision_reasons", args["requestBody"]))
	if err != nil {
		return nil, err
	}
	return decodeBody(resp.Body)
},

"show_work_order_estimate": func(ctx context.Context, t *testing.T, c *wenmar.Client, args map[string]interface{}) (interface{}, error) {
	resp, err := c.ShowWorkOrderEstimate(ctx, intArg(args["pathParams"], "work_order_id"))
	if err != nil {
		return nil, err
	}
	return decodeBody(resp.Body)
},

"show_work_order_inspection": func(ctx context.Context, t *testing.T, c *wenmar.Client, args map[string]interface{}) (interface{}, error) {
	resp, err := c.ShowWorkOrderInspection(ctx, intArg(args["pathParams"], "work_order_id"))
	if err != nil {
		return nil, err
	}
	return decodeBody(resp.Body)
},

"close_work_order": func(ctx context.Context, t *testing.T, c *wenmar.Client, args map[string]interface{}) (interface{}, error) {
	resp, err := c.CloseWorkOrder(ctx, intArg(args["pathParams"], "work_order_id"), CloseWorkOrderRequest{ClosureType: flatVal(args["requestBody"], "closure_type"), ClosureReason: flatVal(args["requestBody"], "closure_reason")})
	if err != nil {
		return nil, err
	}
	return decodeBody(resp.Body)
},

"close_work_order_as_paid": func(ctx context.Context, t *testing.T, c *wenmar.Client, args map[string]interface{}) (interface{}, error) {
	resp, err := c.CloseWorkOrderAsPaid(ctx, intArg(args["pathParams"], "work_order_id"), CloseWorkOrderAsPaidRequest{})
	if err != nil {
		return nil, err
	}
	return decodeBody(resp.Body)
},

"decline_all_work_order_services": func(ctx context.Context, t *testing.T, c *wenmar.Client, args map[string]interface{}) (interface{}, error) {
	resp, err := c.DeclineAllWorkOrderServices(ctx, intArg(args["pathParams"], "work_order_id"), buildWrapper[DeclineAllWorkOrderServicesRequest]("decline_reason", args["requestBody"]))
	if err != nil {
		return nil, err
	}
	return decodeBody(resp.Body)
},

"reopen_work_order": func(ctx context.Context, t *testing.T, c *wenmar.Client, args map[string]interface{}) (interface{}, error) {
	resp, err := c.ReopenWorkOrder(ctx, intArg(args["pathParams"], "work_order_id"), ReopenWorkOrderRequest{})
	if err != nil {
		return nil, err
	}
	return decodeBody(resp.Body)
},

"return_work_order_to_board": func(ctx context.Context, t *testing.T, c *wenmar.Client, args map[string]interface{}) (interface{}, error) {
	resp, err := c.ReturnWorkOrderToBoard(ctx, intArg(args["pathParams"], "work_order_id"), ReturnWorkOrderToBoardRequest{})
	if err != nil {
		return nil, err
	}
	return decodeBody(resp.Body)
},

"save_work_order_for_later": func(ctx context.Context, t *testing.T, c *wenmar.Client, args map[string]interface{}) (interface{}, error) {
	resp, err := c.SaveWorkOrderForLater(ctx, intArg(args["pathParams"], "work_order_id"), SaveWorkOrderForLaterRequest{})
	if err != nil {
		return nil, err
	}
	return decodeBody(resp.Body)
},

"stage_transition_work_order": func(ctx context.Context, t *testing.T, c *wenmar.Client, args map[string]interface{}) (interface{}, error) {
	resp, err := c.StageTransitionWorkOrder(ctx, intArg(args["pathParams"], "work_order_id"), buildWrapper[StageTransitionWorkOrderRequest]("target", args["requestBody"]))
	if err != nil {
		return nil, err
	}
	return decodeBody(resp.Body)
},

"show_work_order_parts": func(ctx context.Context, t *testing.T, c *wenmar.Client, args map[string]interface{}) (interface{}, error) {
	resp, err := c.ShowWorkOrderParts(ctx, intArg(args["pathParams"], "work_order_id"))
	if err != nil {
		return nil, err
	}
	return decodeBody(resp.Body)
},

"show_work_order_payments": func(ctx context.Context, t *testing.T, c *wenmar.Client, args map[string]interface{}) (interface{}, error) {
	resp, err := c.ShowWorkOrderPayments(ctx, intArg(args["pathParams"], "work_order_id"))
	if err != nil {
		return nil, err
	}
	return decodeBody(resp.Body)
},

"create_work_order_payment": func(ctx context.Context, t *testing.T, c *wenmar.Client, args map[string]interface{}) (interface{}, error) {
	resp, err := c.CreateWorkOrderPayment(ctx, intArg(args["pathParams"], "work_order_id"), buildWrapper[CreateWorkOrderPaymentRequest]("payment", args["requestBody"]))
	if err != nil {
		return nil, err
	}
	return decodeBody(resp.Body)
},

"show_work_order_wip": func(ctx context.Context, t *testing.T, c *wenmar.Client, args map[string]interface{}) (interface{}, error) {
	resp, err := c.ShowWorkOrderWip(ctx, intArg(args["pathParams"], "work_order_id"))
	if err != nil {
		return nil, err
	}
	return decodeBody(resp.Body)
},

"list_customer_vehicles": func(ctx context.Context, t *testing.T, c *wenmar.Client, args map[string]interface{}) (interface{}, error) {
	resp, err := c.ListCustomersVehicles(ctx, intArg(args["pathParams"], "customer_id"))
	if err != nil {
		return nil, err
	}
	return decodeBody(resp.Body)
},

"list_customer_work_orders": func(ctx context.Context, t *testing.T, c *wenmar.Client, args map[string]interface{}) (interface{}, error) {
	resp, err := c.ListCustomersWorkOrders(ctx, intArg(args["pathParams"], "customer_id"))
	if err != nil {
		return nil, err
	}
	return decodeBody(resp.Body)
},

"list_vehicle_work_orders": func(ctx context.Context, t *testing.T, c *wenmar.Client, args map[string]interface{}) (interface{}, error) {
	resp, err := c.ListVehiclesWorkOrders(ctx, intArg(args["pathParams"], "vehicle_id"))
	if err != nil {
		return nil, err
	}
	return decodeBody(resp.Body)
},

"list_customers_with_params": func(ctx context.Context, t *testing.T, c *wenmar.Client, args map[string]interface{}) (interface{}, error) {
	resp, err := c.ListCustomers(ctx, &ListCustomersParams{HasBalance: ptrVal(args["query"], "has_balance"), HasVehicle: ptrVal(args["query"], "has_vehicle"), LastVisitMonths: ptrVal(args["query"], "last_visit_months"), Page: ptrVal(args["query"], "page"), PerPage: ptrVal(args["query"], "per_page"), Query: ptrVal(args["query"], "query"), TagIds: ptrVal(args["query"], "tag_ids"), Type: ptrVal(args["query"], "type")})
	if err != nil {
		return nil, err
	}
	return decodeBody(resp.Body)
},

"list_customers_with_params_paginated": func(ctx context.Context, t *testing.T, c *wenmar.Client, args map[string]interface{}) (interface{}, error) {
	resp, err := c.ListCustomers(ctx, &ListCustomersParams{HasBalance: ptrVal(args["query"], "has_balance"), HasVehicle: ptrVal(args["query"], "has_vehicle"), LastVisitMonths: ptrVal(args["query"], "last_visit_months"), Page: ptrVal(args["query"], "page"), PerPage: ptrVal(args["query"], "per_page"), Query: ptrVal(args["query"], "query"), TagIds: ptrVal(args["query"], "tag_ids"), Type: ptrVal(args["query"], "type")})
	if err != nil {
		return nil, err
	}
	return decodeBody(resp.Body)
},

"list_customers_paginated": func(ctx context.Context, t *testing.T, c *wenmar.Client, args map[string]interface{}) (interface{}, error) {
	resp, err := c.ListCustomers(ctx, &ListCustomersParams{HasBalance: ptrVal(args["query"], "has_balance"), HasVehicle: ptrVal(args["query"], "has_vehicle"), LastVisitMonths: ptrVal(args["query"], "last_visit_months"), Page: ptrVal(args["query"], "page"), PerPage: ptrVal(args["query"], "per_page"), Query: ptrVal(args["query"], "query"), TagIds: ptrVal(args["query"], "tag_ids"), Type: ptrVal(args["query"], "type")})
	if err != nil {
		return nil, err
	}
	return decodeBody(resp.Body)
},

"list_work_orders_paginated": func(ctx context.Context, t *testing.T, c *wenmar.Client, args map[string]interface{}) (interface{}, error) {
	resp, err := c.ListWorkOrders(ctx)
	if err != nil {
		return nil, err
	}
	return decodeBody(resp.Body)
},

"check_duplicate": func(ctx context.Context, t *testing.T, c *wenmar.Client, args map[string]interface{}) (interface{}, error) {
	resp, err := c.CheckVehicleDuplicate(ctx, &CheckVehicleDuplicateParams{Vin: ptrVal(args["query"], "vin")})
	if err != nil {
		return nil, err
	}
	return decodeBody(resp.Body)
},


}

// allOperations lists every operation covered by the dispatch map.
var allOperations = []string{
	"list_account",
	"list_customer_tags",
	"create_customer_tag",
	"delete_customer_tag",
	"update_customer_tag",
	"list_customers",
	"create_customer",
	"check_customer_duplicate",
	"lookup_customer",
	"list_customers_drivers",
	"create_driver",
	"delete_driver",
	"show_driver",
	"update_driver",
	"list_customers_statements",
	"list_customers_vehicles",
	"get_customers_vehicle_history",
	"list_customers_work_orders",
	"delete_customer",
	"show_customer",
	"update_customer",
	"merge_customer",
	"show_location",
	"list_service_categories",
	"create_service_category",
	"seed_defaults_service_categories",
	"delete_service_category",
	"update_service_category",
	"deactivate_service_category",
	"move_down_service_category",
	"move_up_service_category",
	"reactivate_service_category",
	"list_tags",
	"update_tags",
	"show_statement",
	"list_team",
	"list_vehicle_tags",
	"create_vehicle_tag",
	"delete_vehicle_tag",
	"update_vehicle_tag",
	"list_vehicles",
	"create_vehicle",
	"check_vehicle_duplicate",
	"lookup_vehicle",
	"prefill_vehicle",
	"decode_vin",
	"delete_vehicle",
	"show_vehicle",
	"update_vehicle",
	"merge_vehicle",
	"transfer_vehicle",
	"list_vehicles_work_orders",
	"list_vendors",
	"show_vendor",
	"list_work_orders",
	"create_work_order",
	"delete_work_order",
	"show_work_order",
	"update_work_order",
	"show_work_order_declined_services",
	"show_work_order_service_history",
	"create_work_order_authorization",
	"update_work_order_authorization_decisions",
	"show_work_order_estimate",
	"show_work_order_inspection",
	"close_work_order",
	"close_work_order_as_paid",
	"decline_all_work_order_services",
	"reopen_work_order",
	"return_work_order_to_board",
	"save_work_order_for_later",
	"stage_transition_work_order",
	"show_work_order_parts",
	"show_work_order_payments",
	"create_work_order_payment",
	"show_work_order_wip",
	"list_customer_vehicles",
	"list_customer_work_orders",
	"list_vehicle_work_orders",
	"list_customers_with_params",
	"list_customers_with_params_paginated",
	"list_customers_paginated",
	"list_work_orders_paginated",
	"check_duplicate"
}
