// Code generated by scripts/generate_go_wrapper.rb from spec/operations.json. DO NOT EDIT.

package wenmar

import gen "github.com/wenmar-pro/wenmar-sdk/go/pkg/generated"

type (
	Customer = gen.Customer
	Driver = gen.Driver
	Statement = gen.Statement
	Vehicle = gen.Vehicle
	WorkOrder = gen.WorkOrder
	ServiceCategory = gen.ServiceCategory
	Vendor = gen.Vendor
	ListAccountResponse = gen.ListAccountResponse
	ListCustomerTagsResponse = gen.ListCustomerTagsResponse
	CreateCustomerTagResponse = gen.CreateCustomerTagResponse
	DeleteCustomerTagResponse = gen.DeleteCustomerTagResponse
	UpdateCustomerTagResponse = gen.UpdateCustomerTagResponse
	ListCustomersResponse = gen.ListCustomersResponse
	CreateCustomerResponse = gen.CreateCustomerResponse
	CheckCustomerDuplicateResponse = gen.CheckCustomerDuplicateResponse
	LookupCustomerResponse = gen.LookupCustomerResponse
	ListCustomersDriversResponse = gen.ListCustomersDriversResponse
	CreateDriverResponse = gen.CreateDriverResponse
	DeleteDriverResponse = gen.DeleteDriverResponse
	ShowDriverResponse = gen.ShowDriverResponse
	UpdateDriverResponse = gen.UpdateDriverResponse
	ListCustomersStatementsResponse = gen.ListCustomersStatementsResponse
	ListCustomersVehiclesResponse = gen.ListCustomersVehiclesResponse
	GetCustomersVehicleHistoryResponse = gen.GetCustomersVehicleHistoryResponse
	ListCustomersWorkOrdersResponse = gen.ListCustomersWorkOrdersResponse
	DeleteCustomerResponse = gen.DeleteCustomerResponse
	ShowCustomerResponse = gen.ShowCustomerResponse
	UpdateCustomerResponse = gen.UpdateCustomerResponse
	MergeCustomerResponse = gen.MergeCustomerResponse
	ShowLocationResponse = gen.ShowLocationResponse
	ListServiceCategoriesResponse = gen.ListServiceCategoriesResponse
	CreateServiceCategoryResponse = gen.CreateServiceCategoryResponse
	SeedDefaultsServiceCategoriesResponse = gen.SeedDefaultsServiceCategoriesResponse
	DeleteServiceCategoryResponse = gen.DeleteServiceCategoryResponse
	UpdateServiceCategoryResponse = gen.UpdateServiceCategoryResponse
	DeactivateServiceCategoryResponse = gen.DeactivateServiceCategoryResponse
	MoveDownServiceCategoryResponse = gen.MoveDownServiceCategoryResponse
	MoveUpServiceCategoryResponse = gen.MoveUpServiceCategoryResponse
	ReactivateServiceCategoryResponse = gen.ReactivateServiceCategoryResponse
	ListTagsResponse = gen.ListTagsResponse
	UpdateTagsResponse = gen.UpdateTagsResponse
	ShowStatementResponse = gen.ShowStatementResponse
	ListTeamResponse = gen.ListTeamResponse
	ListVehicleTagsResponse = gen.ListVehicleTagsResponse
	CreateVehicleTagResponse = gen.CreateVehicleTagResponse
	DeleteVehicleTagResponse = gen.DeleteVehicleTagResponse
	UpdateVehicleTagResponse = gen.UpdateVehicleTagResponse
	ListVehiclesResponse = gen.ListVehiclesResponse
	CreateVehicleResponse = gen.CreateVehicleResponse
	CheckVehicleDuplicateResponse = gen.CheckVehicleDuplicateResponse
	LookupVehicleResponse = gen.LookupVehicleResponse
	PrefillVehicleResponse = gen.PrefillVehicleResponse
	DecodeVinResponse = gen.DecodeVinResponse
	DeleteVehicleResponse = gen.DeleteVehicleResponse
	ShowVehicleResponse = gen.ShowVehicleResponse
	UpdateVehicleResponse = gen.UpdateVehicleResponse
	MergeVehicleResponse = gen.MergeVehicleResponse
	TransferVehicleResponse = gen.TransferVehicleResponse
	ListVehiclesWorkOrdersResponse = gen.ListVehiclesWorkOrdersResponse
	ListVendorsResponse = gen.ListVendorsResponse
	ShowVendorResponse = gen.ShowVendorResponse
	ListWorkOrdersResponse = gen.ListWorkOrdersResponse
	CreateWorkOrderResponse = gen.CreateWorkOrderResponse
	DeleteWorkOrderResponse = gen.DeleteWorkOrderResponse
	ShowWorkOrderResponse = gen.ShowWorkOrderResponse
	UpdateWorkOrderResponse = gen.UpdateWorkOrderResponse
	ShowWorkOrderDeclinedServicesResponse = gen.ShowWorkOrderDeclinedServicesResponse
	ShowWorkOrderServiceHistoryResponse = gen.ShowWorkOrderServiceHistoryResponse
	CreateWorkOrderAuthorizationResponse = gen.CreateWorkOrderAuthorizationResponse
	UpdateWorkOrderAuthorizationDecisionsResponse = gen.UpdateWorkOrderAuthorizationDecisionsResponse
	ShowWorkOrderEstimateResponse = gen.ShowWorkOrderEstimateResponse
	ShowWorkOrderInspectionResponse = gen.ShowWorkOrderInspectionResponse
	CloseWorkOrderResponse = gen.CloseWorkOrderResponse
	CloseWorkOrderAsPaidResponse = gen.CloseWorkOrderAsPaidResponse
	DeclineAllWorkOrderServicesResponse = gen.DeclineAllWorkOrderServicesResponse
	ReopenWorkOrderResponse = gen.ReopenWorkOrderResponse
	ReturnWorkOrderToBoardResponse = gen.ReturnWorkOrderToBoardResponse
	SaveWorkOrderForLaterResponse = gen.SaveWorkOrderForLaterResponse
	StageTransitionWorkOrderResponse = gen.StageTransitionWorkOrderResponse
	ShowWorkOrderPartsResponse = gen.ShowWorkOrderPartsResponse
	ShowWorkOrderPaymentsResponse = gen.ShowWorkOrderPaymentsResponse
	CreateWorkOrderPaymentResponse = gen.CreateWorkOrderPaymentResponse
	ShowWorkOrderWipResponse = gen.ShowWorkOrderWipResponse
)

type (
	CreateCustomerTagRequest = gen.CreateCustomerTagRequest
	UpdateCustomerTagRequest = gen.UpdateCustomerTagRequest
	CreateCustomerRequest = gen.CreateCustomerRequest
	CreateDriverRequest = gen.CreateDriverRequest
	UpdateDriverRequest = gen.UpdateDriverRequest
	UpdateCustomerRequest = gen.UpdateCustomerRequest
	MergeCustomerRequest = gen.MergeCustomerRequest
	CreateServiceCategoryRequest = gen.CreateServiceCategoryRequest
	SeedDefaultsServiceCategoriesRequest = gen.SeedDefaultsServiceCategoriesRequest
	UpdateServiceCategoryRequest = gen.UpdateServiceCategoryRequest
	DeactivateServiceCategoryRequest = gen.DeactivateServiceCategoryRequest
	MoveDownServiceCategoryRequest = gen.MoveDownServiceCategoryRequest
	MoveUpServiceCategoryRequest = gen.MoveUpServiceCategoryRequest
	ReactivateServiceCategoryRequest = gen.ReactivateServiceCategoryRequest
	UpdateTagsRequest = gen.UpdateTagsRequest
	CreateVehicleTagRequest = gen.CreateVehicleTagRequest
	UpdateVehicleTagRequest = gen.UpdateVehicleTagRequest
	CreateVehicleRequest = gen.CreateVehicleRequest
	UpdateVehicleRequest = gen.UpdateVehicleRequest
	MergeVehicleRequest = gen.MergeVehicleRequest
	TransferVehicleRequest = gen.TransferVehicleRequest
	CreateWorkOrderRequest = gen.CreateWorkOrderRequest
	UpdateWorkOrderRequest = gen.UpdateWorkOrderRequest
	CreateWorkOrderAuthorizationRequest = gen.CreateWorkOrderAuthorizationRequest
	UpdateWorkOrderAuthorizationDecisionsRequest = gen.UpdateWorkOrderAuthorizationDecisionsRequest
	CloseWorkOrderRequest = gen.CloseWorkOrderRequest
	CloseWorkOrderAsPaidRequest = gen.CloseWorkOrderAsPaidRequest
	DeclineAllWorkOrderServicesRequest = gen.DeclineAllWorkOrderServicesRequest
	ReopenWorkOrderRequest = gen.ReopenWorkOrderRequest
	ReturnWorkOrderToBoardRequest = gen.ReturnWorkOrderToBoardRequest
	SaveWorkOrderForLaterRequest = gen.SaveWorkOrderForLaterRequest
	StageTransitionWorkOrderRequest = gen.StageTransitionWorkOrderRequest
	CreateWorkOrderPaymentRequest = gen.CreateWorkOrderPaymentRequest
)

type (
	ListCustomersParams = gen.ListCustomersParams
	CheckCustomerDuplicateParams = gen.CheckCustomerDuplicateParams
	LookupCustomerParams = gen.LookupCustomerParams
	ListVehiclesParams = gen.ListVehiclesParams
	CheckVehicleDuplicateParams = gen.CheckVehicleDuplicateParams
	LookupVehicleParams = gen.LookupVehicleParams
	PrefillVehicleParams = gen.PrefillVehicleParams
	DecodeVinParams = gen.DecodeVinParams
)
