// Code generated by scripts/generate_go_wrapper.rb from spec/operations.json. DO NOT EDIT.
//go:build !skip_generate

package wenmar

import "context"

// ListAccount runs the list_account operation (GET /account).
func (c *Client) ListAccount(ctx context.Context) (*ListAccountResponse, error) {
	ctx = c.hooks.OnOperationStart(ctx, OperationInfo{Operation: "ListAccount"})
	resp, err := c.gen.ListAccountWithResponse(ctx)
	if err != nil {
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "ListAccount"}, OperationResult{Operation: "ListAccount", Err: err})
		return nil, err
	}
	if resp.StatusCode() >= 400 {
		perr := parseError(resp.Body, resp.StatusCode(), resp.HTTPResponse)
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "ListAccount"}, OperationResult{Operation: "ListAccount", Err: perr})
		return nil, perr
	}
	c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "ListAccount"}, OperationResult{Operation: "ListAccount"})
	return resp, nil
}

// ListCustomerTags runs the list_customer_tags operation (GET /customer_tags).
func (c *Client) ListCustomerTags(ctx context.Context) (*ListCustomerTagsResponse, error) {
	ctx = c.hooks.OnOperationStart(ctx, OperationInfo{Operation: "ListCustomerTags"})
	resp, err := c.gen.ListCustomerTagsWithResponse(ctx)
	if err != nil {
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "ListCustomerTags"}, OperationResult{Operation: "ListCustomerTags", Err: err})
		return nil, err
	}
	if resp.StatusCode() >= 400 {
		perr := parseError(resp.Body, resp.StatusCode(), resp.HTTPResponse)
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "ListCustomerTags"}, OperationResult{Operation: "ListCustomerTags", Err: perr})
		return nil, perr
	}
	c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "ListCustomerTags"}, OperationResult{Operation: "ListCustomerTags"})
	return resp, nil
}

// CreateCustomerTag runs the create_customer_tag operation (POST /customer_tags).
func (c *Client) CreateCustomerTag(ctx context.Context, body CreateCustomerTagRequest) (*CreateCustomerTagResponse, error) {
	ctx = c.hooks.OnOperationStart(ctx, OperationInfo{Operation: "CreateCustomerTag"})
	resp, err := c.gen.CreateCustomerTagWithResponse(ctx, body)
	if err != nil {
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "CreateCustomerTag"}, OperationResult{Operation: "CreateCustomerTag", Err: err})
		return nil, err
	}
	if resp.StatusCode() >= 400 {
		perr := parseError(resp.Body, resp.StatusCode(), resp.HTTPResponse)
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "CreateCustomerTag"}, OperationResult{Operation: "CreateCustomerTag", Err: perr})
		return nil, perr
	}
	c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "CreateCustomerTag"}, OperationResult{Operation: "CreateCustomerTag"})
	return resp, nil
}

// DeleteCustomerTag runs the delete_customer_tag operation (DELETE /customer_tags/{id}).
func (c *Client) DeleteCustomerTag(ctx context.Context, id int) (*DeleteCustomerTagResponse, error) {
	ctx = c.hooks.OnOperationStart(ctx, OperationInfo{Operation: "DeleteCustomerTag"})
	resp, err := c.gen.DeleteCustomerTagWithResponse(ctx, id)
	if err != nil {
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "DeleteCustomerTag"}, OperationResult{Operation: "DeleteCustomerTag", Err: err})
		return nil, err
	}
	if resp.StatusCode() >= 400 {
		perr := parseError(resp.Body, resp.StatusCode(), resp.HTTPResponse)
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "DeleteCustomerTag"}, OperationResult{Operation: "DeleteCustomerTag", Err: perr})
		return nil, perr
	}
	c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "DeleteCustomerTag"}, OperationResult{Operation: "DeleteCustomerTag"})
	return resp, nil
}

// UpdateCustomerTag runs the update_customer_tag operation (PATCH /customer_tags/{id}).
func (c *Client) UpdateCustomerTag(ctx context.Context, id int, body UpdateCustomerTagRequest) (*UpdateCustomerTagResponse, error) {
	ctx = c.hooks.OnOperationStart(ctx, OperationInfo{Operation: "UpdateCustomerTag"})
	resp, err := c.gen.UpdateCustomerTagWithResponse(ctx, id, body)
	if err != nil {
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "UpdateCustomerTag"}, OperationResult{Operation: "UpdateCustomerTag", Err: err})
		return nil, err
	}
	if resp.StatusCode() >= 400 {
		perr := parseError(resp.Body, resp.StatusCode(), resp.HTTPResponse)
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "UpdateCustomerTag"}, OperationResult{Operation: "UpdateCustomerTag", Err: perr})
		return nil, perr
	}
	c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "UpdateCustomerTag"}, OperationResult{Operation: "UpdateCustomerTag"})
	return resp, nil
}

// ListCustomers runs the list_customers operation (GET /customers).
func (c *Client) ListCustomers(ctx context.Context, params *ListCustomersParams) (*ListCustomersResponse, error) {
	ctx = c.hooks.OnOperationStart(ctx, OperationInfo{Operation: "ListCustomers"})
	resp, err := c.gen.ListCustomersWithResponse(ctx, params)
	if err != nil {
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "ListCustomers"}, OperationResult{Operation: "ListCustomers", Err: err})
		return nil, err
	}
	if resp.StatusCode() >= 400 {
		perr := parseError(resp.Body, resp.StatusCode(), resp.HTTPResponse)
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "ListCustomers"}, OperationResult{Operation: "ListCustomers", Err: perr})
		return nil, perr
	}
	c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "ListCustomers"}, OperationResult{Operation: "ListCustomers"})
	return resp, nil
}

// CreateCustomer runs the create_customer operation (POST /customers).
func (c *Client) CreateCustomer(ctx context.Context, body CreateCustomerRequest) (*CreateCustomerResponse, error) {
	ctx = c.hooks.OnOperationStart(ctx, OperationInfo{Operation: "CreateCustomer"})
	resp, err := c.gen.CreateCustomerWithResponse(ctx, body)
	if err != nil {
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "CreateCustomer"}, OperationResult{Operation: "CreateCustomer", Err: err})
		return nil, err
	}
	if resp.StatusCode() >= 400 {
		perr := parseError(resp.Body, resp.StatusCode(), resp.HTTPResponse)
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "CreateCustomer"}, OperationResult{Operation: "CreateCustomer", Err: perr})
		return nil, perr
	}
	c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "CreateCustomer"}, OperationResult{Operation: "CreateCustomer"})
	return resp, nil
}

// CheckCustomerDuplicate runs the check_customer_duplicate operation (GET /customers/check_duplicate).
func (c *Client) CheckCustomerDuplicate(ctx context.Context, params *CheckCustomerDuplicateParams) (*CheckCustomerDuplicateResponse, error) {
	ctx = c.hooks.OnOperationStart(ctx, OperationInfo{Operation: "CheckCustomerDuplicate"})
	resp, err := c.gen.CheckCustomerDuplicateWithResponse(ctx, params)
	if err != nil {
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "CheckCustomerDuplicate"}, OperationResult{Operation: "CheckCustomerDuplicate", Err: err})
		return nil, err
	}
	if resp.StatusCode() >= 400 {
		perr := parseError(resp.Body, resp.StatusCode(), resp.HTTPResponse)
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "CheckCustomerDuplicate"}, OperationResult{Operation: "CheckCustomerDuplicate", Err: perr})
		return nil, perr
	}
	c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "CheckCustomerDuplicate"}, OperationResult{Operation: "CheckCustomerDuplicate"})
	return resp, nil
}

// LookupCustomer runs the lookup_customer operation (GET /customers/lookup).
func (c *Client) LookupCustomer(ctx context.Context, params *LookupCustomerParams) (*LookupCustomerResponse, error) {
	ctx = c.hooks.OnOperationStart(ctx, OperationInfo{Operation: "LookupCustomer"})
	resp, err := c.gen.LookupCustomerWithResponse(ctx, params)
	if err != nil {
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "LookupCustomer"}, OperationResult{Operation: "LookupCustomer", Err: err})
		return nil, err
	}
	if resp.StatusCode() >= 400 {
		perr := parseError(resp.Body, resp.StatusCode(), resp.HTTPResponse)
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "LookupCustomer"}, OperationResult{Operation: "LookupCustomer", Err: perr})
		return nil, perr
	}
	c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "LookupCustomer"}, OperationResult{Operation: "LookupCustomer"})
	return resp, nil
}

// ListCustomersDrivers runs the list_customers_drivers operation (GET /customers/{customer_id}/drivers).
func (c *Client) ListCustomersDrivers(ctx context.Context, customerId int) (*ListCustomersDriversResponse, error) {
	ctx = c.hooks.OnOperationStart(ctx, OperationInfo{Operation: "ListCustomersDrivers"})
	resp, err := c.gen.ListCustomersDriversWithResponse(ctx, customerId)
	if err != nil {
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "ListCustomersDrivers"}, OperationResult{Operation: "ListCustomersDrivers", Err: err})
		return nil, err
	}
	if resp.StatusCode() >= 400 {
		perr := parseError(resp.Body, resp.StatusCode(), resp.HTTPResponse)
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "ListCustomersDrivers"}, OperationResult{Operation: "ListCustomersDrivers", Err: perr})
		return nil, perr
	}
	c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "ListCustomersDrivers"}, OperationResult{Operation: "ListCustomersDrivers"})
	return resp, nil
}

// CreateDriver runs the create_driver operation (POST /customers/{customer_id}/drivers).
func (c *Client) CreateDriver(ctx context.Context, customerId int, body CreateDriverRequest) (*CreateDriverResponse, error) {
	ctx = c.hooks.OnOperationStart(ctx, OperationInfo{Operation: "CreateDriver"})
	resp, err := c.gen.CreateDriverWithResponse(ctx, customerId, body)
	if err != nil {
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "CreateDriver"}, OperationResult{Operation: "CreateDriver", Err: err})
		return nil, err
	}
	if resp.StatusCode() >= 400 {
		perr := parseError(resp.Body, resp.StatusCode(), resp.HTTPResponse)
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "CreateDriver"}, OperationResult{Operation: "CreateDriver", Err: perr})
		return nil, perr
	}
	c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "CreateDriver"}, OperationResult{Operation: "CreateDriver"})
	return resp, nil
}

// DeleteDriver runs the delete_driver operation (DELETE /customers/{customer_id}/drivers/{id}).
func (c *Client) DeleteDriver(ctx context.Context, customerId int, id int) (*DeleteDriverResponse, error) {
	ctx = c.hooks.OnOperationStart(ctx, OperationInfo{Operation: "DeleteDriver"})
	resp, err := c.gen.DeleteDriverWithResponse(ctx, customerId, id)
	if err != nil {
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "DeleteDriver"}, OperationResult{Operation: "DeleteDriver", Err: err})
		return nil, err
	}
	if resp.StatusCode() >= 400 {
		perr := parseError(resp.Body, resp.StatusCode(), resp.HTTPResponse)
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "DeleteDriver"}, OperationResult{Operation: "DeleteDriver", Err: perr})
		return nil, perr
	}
	c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "DeleteDriver"}, OperationResult{Operation: "DeleteDriver"})
	return resp, nil
}

// ShowDriver runs the show_driver operation (GET /customers/{customer_id}/drivers/{id}).
func (c *Client) ShowDriver(ctx context.Context, customerId int, id int) (*ShowDriverResponse, error) {
	ctx = c.hooks.OnOperationStart(ctx, OperationInfo{Operation: "ShowDriver"})
	resp, err := c.gen.ShowDriverWithResponse(ctx, customerId, id)
	if err != nil {
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "ShowDriver"}, OperationResult{Operation: "ShowDriver", Err: err})
		return nil, err
	}
	if resp.StatusCode() >= 400 {
		perr := parseError(resp.Body, resp.StatusCode(), resp.HTTPResponse)
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "ShowDriver"}, OperationResult{Operation: "ShowDriver", Err: perr})
		return nil, perr
	}
	c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "ShowDriver"}, OperationResult{Operation: "ShowDriver"})
	return resp, nil
}

// UpdateDriver runs the update_driver operation (PATCH /customers/{customer_id}/drivers/{id}).
func (c *Client) UpdateDriver(ctx context.Context, customerId int, id int, body UpdateDriverRequest) (*UpdateDriverResponse, error) {
	ctx = c.hooks.OnOperationStart(ctx, OperationInfo{Operation: "UpdateDriver"})
	resp, err := c.gen.UpdateDriverWithResponse(ctx, customerId, id, body)
	if err != nil {
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "UpdateDriver"}, OperationResult{Operation: "UpdateDriver", Err: err})
		return nil, err
	}
	if resp.StatusCode() >= 400 {
		perr := parseError(resp.Body, resp.StatusCode(), resp.HTTPResponse)
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "UpdateDriver"}, OperationResult{Operation: "UpdateDriver", Err: perr})
		return nil, perr
	}
	c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "UpdateDriver"}, OperationResult{Operation: "UpdateDriver"})
	return resp, nil
}

// ListCustomersStatements runs the list_customers_statements operation (GET /customers/{customer_id}/statements).
func (c *Client) ListCustomersStatements(ctx context.Context, customerId int) (*ListCustomersStatementsResponse, error) {
	ctx = c.hooks.OnOperationStart(ctx, OperationInfo{Operation: "ListCustomersStatements"})
	resp, err := c.gen.ListCustomersStatementsWithResponse(ctx, customerId)
	if err != nil {
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "ListCustomersStatements"}, OperationResult{Operation: "ListCustomersStatements", Err: err})
		return nil, err
	}
	if resp.StatusCode() >= 400 {
		perr := parseError(resp.Body, resp.StatusCode(), resp.HTTPResponse)
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "ListCustomersStatements"}, OperationResult{Operation: "ListCustomersStatements", Err: perr})
		return nil, perr
	}
	c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "ListCustomersStatements"}, OperationResult{Operation: "ListCustomersStatements"})
	return resp, nil
}

// ListCustomersVehicles runs the list_customers_vehicles operation (GET /customers/{customer_id}/vehicles).
func (c *Client) ListCustomersVehicles(ctx context.Context, customerId int) (*ListCustomersVehiclesResponse, error) {
	ctx = c.hooks.OnOperationStart(ctx, OperationInfo{Operation: "ListCustomersVehicles"})
	resp, err := c.gen.ListCustomersVehiclesWithResponse(ctx, customerId)
	if err != nil {
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "ListCustomersVehicles"}, OperationResult{Operation: "ListCustomersVehicles", Err: err})
		return nil, err
	}
	if resp.StatusCode() >= 400 {
		perr := parseError(resp.Body, resp.StatusCode(), resp.HTTPResponse)
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "ListCustomersVehicles"}, OperationResult{Operation: "ListCustomersVehicles", Err: perr})
		return nil, perr
	}
	c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "ListCustomersVehicles"}, OperationResult{Operation: "ListCustomersVehicles"})
	return resp, nil
}

// GetCustomersVehicleHistory runs the get_customers_vehicle_history operation (GET /customers/{customer_id}/vehicles/{vehicle_id}/history).
func (c *Client) GetCustomersVehicleHistory(ctx context.Context, customerId int, vehicleId int) (*GetCustomersVehicleHistoryResponse, error) {
	ctx = c.hooks.OnOperationStart(ctx, OperationInfo{Operation: "GetCustomersVehicleHistory"})
	resp, err := c.gen.GetCustomersVehicleHistoryWithResponse(ctx, customerId, vehicleId)
	if err != nil {
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "GetCustomersVehicleHistory"}, OperationResult{Operation: "GetCustomersVehicleHistory", Err: err})
		return nil, err
	}
	if resp.StatusCode() >= 400 {
		perr := parseError(resp.Body, resp.StatusCode(), resp.HTTPResponse)
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "GetCustomersVehicleHistory"}, OperationResult{Operation: "GetCustomersVehicleHistory", Err: perr})
		return nil, perr
	}
	c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "GetCustomersVehicleHistory"}, OperationResult{Operation: "GetCustomersVehicleHistory"})
	return resp, nil
}

// ListCustomersWorkOrders runs the list_customers_work_orders operation (GET /customers/{customer_id}/work_orders).
func (c *Client) ListCustomersWorkOrders(ctx context.Context, customerId int) (*ListCustomersWorkOrdersResponse, error) {
	ctx = c.hooks.OnOperationStart(ctx, OperationInfo{Operation: "ListCustomersWorkOrders"})
	resp, err := c.gen.ListCustomersWorkOrdersWithResponse(ctx, customerId)
	if err != nil {
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "ListCustomersWorkOrders"}, OperationResult{Operation: "ListCustomersWorkOrders", Err: err})
		return nil, err
	}
	if resp.StatusCode() >= 400 {
		perr := parseError(resp.Body, resp.StatusCode(), resp.HTTPResponse)
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "ListCustomersWorkOrders"}, OperationResult{Operation: "ListCustomersWorkOrders", Err: perr})
		return nil, perr
	}
	c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "ListCustomersWorkOrders"}, OperationResult{Operation: "ListCustomersWorkOrders"})
	return resp, nil
}

// DeleteCustomer runs the delete_customer operation (DELETE /customers/{id}).
func (c *Client) DeleteCustomer(ctx context.Context, id int) (*DeleteCustomerResponse, error) {
	ctx = c.hooks.OnOperationStart(ctx, OperationInfo{Operation: "DeleteCustomer"})
	resp, err := c.gen.DeleteCustomerWithResponse(ctx, id)
	if err != nil {
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "DeleteCustomer"}, OperationResult{Operation: "DeleteCustomer", Err: err})
		return nil, err
	}
	if resp.StatusCode() >= 400 {
		perr := parseError(resp.Body, resp.StatusCode(), resp.HTTPResponse)
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "DeleteCustomer"}, OperationResult{Operation: "DeleteCustomer", Err: perr})
		return nil, perr
	}
	c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "DeleteCustomer"}, OperationResult{Operation: "DeleteCustomer"})
	return resp, nil
}

// ShowCustomer runs the show_customer operation (GET /customers/{id}).
func (c *Client) ShowCustomer(ctx context.Context, id int) (*ShowCustomerResponse, error) {
	ctx = c.hooks.OnOperationStart(ctx, OperationInfo{Operation: "ShowCustomer"})
	resp, err := c.gen.ShowCustomerWithResponse(ctx, id)
	if err != nil {
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "ShowCustomer"}, OperationResult{Operation: "ShowCustomer", Err: err})
		return nil, err
	}
	if resp.StatusCode() >= 400 {
		perr := parseError(resp.Body, resp.StatusCode(), resp.HTTPResponse)
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "ShowCustomer"}, OperationResult{Operation: "ShowCustomer", Err: perr})
		return nil, perr
	}
	c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "ShowCustomer"}, OperationResult{Operation: "ShowCustomer"})
	return resp, nil
}

// UpdateCustomer runs the update_customer operation (PATCH /customers/{id}).
func (c *Client) UpdateCustomer(ctx context.Context, id int, body UpdateCustomerRequest) (*UpdateCustomerResponse, error) {
	ctx = c.hooks.OnOperationStart(ctx, OperationInfo{Operation: "UpdateCustomer"})
	resp, err := c.gen.UpdateCustomerWithResponse(ctx, id, body)
	if err != nil {
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "UpdateCustomer"}, OperationResult{Operation: "UpdateCustomer", Err: err})
		return nil, err
	}
	if resp.StatusCode() >= 400 {
		perr := parseError(resp.Body, resp.StatusCode(), resp.HTTPResponse)
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "UpdateCustomer"}, OperationResult{Operation: "UpdateCustomer", Err: perr})
		return nil, perr
	}
	c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "UpdateCustomer"}, OperationResult{Operation: "UpdateCustomer"})
	return resp, nil
}

// MergeCustomer runs the merge_customer operation (POST /customers/{id}/merge).
func (c *Client) MergeCustomer(ctx context.Context, id int, body MergeCustomerRequest) (*MergeCustomerResponse, error) {
	ctx = c.hooks.OnOperationStart(ctx, OperationInfo{Operation: "MergeCustomer"})
	resp, err := c.gen.MergeCustomerWithResponse(ctx, id, body)
	if err != nil {
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "MergeCustomer"}, OperationResult{Operation: "MergeCustomer", Err: err})
		return nil, err
	}
	if resp.StatusCode() >= 400 {
		perr := parseError(resp.Body, resp.StatusCode(), resp.HTTPResponse)
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "MergeCustomer"}, OperationResult{Operation: "MergeCustomer", Err: perr})
		return nil, perr
	}
	c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "MergeCustomer"}, OperationResult{Operation: "MergeCustomer"})
	return resp, nil
}

// ShowLocation runs the show_location operation (GET /locations/{id}).
func (c *Client) ShowLocation(ctx context.Context, id string) (*ShowLocationResponse, error) {
	ctx = c.hooks.OnOperationStart(ctx, OperationInfo{Operation: "ShowLocation"})
	resp, err := c.gen.ShowLocationWithResponse(ctx, id)
	if err != nil {
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "ShowLocation"}, OperationResult{Operation: "ShowLocation", Err: err})
		return nil, err
	}
	if resp.StatusCode() >= 400 {
		perr := parseError(resp.Body, resp.StatusCode(), resp.HTTPResponse)
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "ShowLocation"}, OperationResult{Operation: "ShowLocation", Err: perr})
		return nil, perr
	}
	c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "ShowLocation"}, OperationResult{Operation: "ShowLocation"})
	return resp, nil
}

// ListServiceCategories runs the list_service_categories operation (GET /service_categories).
func (c *Client) ListServiceCategories(ctx context.Context) (*ListServiceCategoriesResponse, error) {
	ctx = c.hooks.OnOperationStart(ctx, OperationInfo{Operation: "ListServiceCategories"})
	resp, err := c.gen.ListServiceCategoriesWithResponse(ctx)
	if err != nil {
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "ListServiceCategories"}, OperationResult{Operation: "ListServiceCategories", Err: err})
		return nil, err
	}
	if resp.StatusCode() >= 400 {
		perr := parseError(resp.Body, resp.StatusCode(), resp.HTTPResponse)
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "ListServiceCategories"}, OperationResult{Operation: "ListServiceCategories", Err: perr})
		return nil, perr
	}
	c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "ListServiceCategories"}, OperationResult{Operation: "ListServiceCategories"})
	return resp, nil
}

// CreateServiceCategory runs the create_service_category operation (POST /service_categories).
func (c *Client) CreateServiceCategory(ctx context.Context, body CreateServiceCategoryRequest) (*CreateServiceCategoryResponse, error) {
	ctx = c.hooks.OnOperationStart(ctx, OperationInfo{Operation: "CreateServiceCategory"})
	resp, err := c.gen.CreateServiceCategoryWithResponse(ctx, body)
	if err != nil {
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "CreateServiceCategory"}, OperationResult{Operation: "CreateServiceCategory", Err: err})
		return nil, err
	}
	if resp.StatusCode() >= 400 {
		perr := parseError(resp.Body, resp.StatusCode(), resp.HTTPResponse)
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "CreateServiceCategory"}, OperationResult{Operation: "CreateServiceCategory", Err: perr})
		return nil, perr
	}
	c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "CreateServiceCategory"}, OperationResult{Operation: "CreateServiceCategory"})
	return resp, nil
}

// SeedDefaultsServiceCategories runs the seed_defaults_service_categories operation (POST /service_categories/seed_defaults).
func (c *Client) SeedDefaultsServiceCategories(ctx context.Context, body SeedDefaultsServiceCategoriesRequest) (*SeedDefaultsServiceCategoriesResponse, error) {
	ctx = c.hooks.OnOperationStart(ctx, OperationInfo{Operation: "SeedDefaultsServiceCategories"})
	resp, err := c.gen.SeedDefaultsServiceCategoriesWithResponse(ctx, body)
	if err != nil {
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "SeedDefaultsServiceCategories"}, OperationResult{Operation: "SeedDefaultsServiceCategories", Err: err})
		return nil, err
	}
	if resp.StatusCode() >= 400 {
		perr := parseError(resp.Body, resp.StatusCode(), resp.HTTPResponse)
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "SeedDefaultsServiceCategories"}, OperationResult{Operation: "SeedDefaultsServiceCategories", Err: perr})
		return nil, perr
	}
	c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "SeedDefaultsServiceCategories"}, OperationResult{Operation: "SeedDefaultsServiceCategories"})
	return resp, nil
}

// DeleteServiceCategory runs the delete_service_category operation (DELETE /service_categories/{id}).
func (c *Client) DeleteServiceCategory(ctx context.Context, id int) (*DeleteServiceCategoryResponse, error) {
	ctx = c.hooks.OnOperationStart(ctx, OperationInfo{Operation: "DeleteServiceCategory"})
	resp, err := c.gen.DeleteServiceCategoryWithResponse(ctx, id)
	if err != nil {
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "DeleteServiceCategory"}, OperationResult{Operation: "DeleteServiceCategory", Err: err})
		return nil, err
	}
	if resp.StatusCode() >= 400 {
		perr := parseError(resp.Body, resp.StatusCode(), resp.HTTPResponse)
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "DeleteServiceCategory"}, OperationResult{Operation: "DeleteServiceCategory", Err: perr})
		return nil, perr
	}
	c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "DeleteServiceCategory"}, OperationResult{Operation: "DeleteServiceCategory"})
	return resp, nil
}

// UpdateServiceCategory runs the update_service_category operation (PATCH /service_categories/{id}).
func (c *Client) UpdateServiceCategory(ctx context.Context, id int, body UpdateServiceCategoryRequest) (*UpdateServiceCategoryResponse, error) {
	ctx = c.hooks.OnOperationStart(ctx, OperationInfo{Operation: "UpdateServiceCategory"})
	resp, err := c.gen.UpdateServiceCategoryWithResponse(ctx, id, body)
	if err != nil {
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "UpdateServiceCategory"}, OperationResult{Operation: "UpdateServiceCategory", Err: err})
		return nil, err
	}
	if resp.StatusCode() >= 400 {
		perr := parseError(resp.Body, resp.StatusCode(), resp.HTTPResponse)
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "UpdateServiceCategory"}, OperationResult{Operation: "UpdateServiceCategory", Err: perr})
		return nil, perr
	}
	c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "UpdateServiceCategory"}, OperationResult{Operation: "UpdateServiceCategory"})
	return resp, nil
}

// DeactivateServiceCategory runs the deactivate_service_category operation (PATCH /service_categories/{id}/deactivate).
func (c *Client) DeactivateServiceCategory(ctx context.Context, id int, body DeactivateServiceCategoryRequest) (*DeactivateServiceCategoryResponse, error) {
	ctx = c.hooks.OnOperationStart(ctx, OperationInfo{Operation: "DeactivateServiceCategory"})
	resp, err := c.gen.DeactivateServiceCategoryWithResponse(ctx, id, body)
	if err != nil {
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "DeactivateServiceCategory"}, OperationResult{Operation: "DeactivateServiceCategory", Err: err})
		return nil, err
	}
	if resp.StatusCode() >= 400 {
		perr := parseError(resp.Body, resp.StatusCode(), resp.HTTPResponse)
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "DeactivateServiceCategory"}, OperationResult{Operation: "DeactivateServiceCategory", Err: perr})
		return nil, perr
	}
	c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "DeactivateServiceCategory"}, OperationResult{Operation: "DeactivateServiceCategory"})
	return resp, nil
}

// MoveDownServiceCategory runs the move_down_service_category operation (PATCH /service_categories/{id}/move_down).
func (c *Client) MoveDownServiceCategory(ctx context.Context, id int, body MoveDownServiceCategoryRequest) (*MoveDownServiceCategoryResponse, error) {
	ctx = c.hooks.OnOperationStart(ctx, OperationInfo{Operation: "MoveDownServiceCategory"})
	resp, err := c.gen.MoveDownServiceCategoryWithResponse(ctx, id, body)
	if err != nil {
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "MoveDownServiceCategory"}, OperationResult{Operation: "MoveDownServiceCategory", Err: err})
		return nil, err
	}
	if resp.StatusCode() >= 400 {
		perr := parseError(resp.Body, resp.StatusCode(), resp.HTTPResponse)
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "MoveDownServiceCategory"}, OperationResult{Operation: "MoveDownServiceCategory", Err: perr})
		return nil, perr
	}
	c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "MoveDownServiceCategory"}, OperationResult{Operation: "MoveDownServiceCategory"})
	return resp, nil
}

// MoveUpServiceCategory runs the move_up_service_category operation (PATCH /service_categories/{id}/move_up).
func (c *Client) MoveUpServiceCategory(ctx context.Context, id int, body MoveUpServiceCategoryRequest) (*MoveUpServiceCategoryResponse, error) {
	ctx = c.hooks.OnOperationStart(ctx, OperationInfo{Operation: "MoveUpServiceCategory"})
	resp, err := c.gen.MoveUpServiceCategoryWithResponse(ctx, id, body)
	if err != nil {
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "MoveUpServiceCategory"}, OperationResult{Operation: "MoveUpServiceCategory", Err: err})
		return nil, err
	}
	if resp.StatusCode() >= 400 {
		perr := parseError(resp.Body, resp.StatusCode(), resp.HTTPResponse)
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "MoveUpServiceCategory"}, OperationResult{Operation: "MoveUpServiceCategory", Err: perr})
		return nil, perr
	}
	c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "MoveUpServiceCategory"}, OperationResult{Operation: "MoveUpServiceCategory"})
	return resp, nil
}

// ReactivateServiceCategory runs the reactivate_service_category operation (PATCH /service_categories/{id}/reactivate).
func (c *Client) ReactivateServiceCategory(ctx context.Context, id int, body ReactivateServiceCategoryRequest) (*ReactivateServiceCategoryResponse, error) {
	ctx = c.hooks.OnOperationStart(ctx, OperationInfo{Operation: "ReactivateServiceCategory"})
	resp, err := c.gen.ReactivateServiceCategoryWithResponse(ctx, id, body)
	if err != nil {
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "ReactivateServiceCategory"}, OperationResult{Operation: "ReactivateServiceCategory", Err: err})
		return nil, err
	}
	if resp.StatusCode() >= 400 {
		perr := parseError(resp.Body, resp.StatusCode(), resp.HTTPResponse)
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "ReactivateServiceCategory"}, OperationResult{Operation: "ReactivateServiceCategory", Err: perr})
		return nil, perr
	}
	c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "ReactivateServiceCategory"}, OperationResult{Operation: "ReactivateServiceCategory"})
	return resp, nil
}

// ListTags runs the list_tags operation (GET /settings/tags).
func (c *Client) ListTags(ctx context.Context) (*ListTagsResponse, error) {
	ctx = c.hooks.OnOperationStart(ctx, OperationInfo{Operation: "ListTags"})
	resp, err := c.gen.ListTagsWithResponse(ctx)
	if err != nil {
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "ListTags"}, OperationResult{Operation: "ListTags", Err: err})
		return nil, err
	}
	if resp.StatusCode() >= 400 {
		perr := parseError(resp.Body, resp.StatusCode(), resp.HTTPResponse)
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "ListTags"}, OperationResult{Operation: "ListTags", Err: perr})
		return nil, perr
	}
	c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "ListTags"}, OperationResult{Operation: "ListTags"})
	return resp, nil
}

// UpdateTags runs the update_tags operation (PATCH /settings/tags).
func (c *Client) UpdateTags(ctx context.Context, body UpdateTagsRequest) (*UpdateTagsResponse, error) {
	ctx = c.hooks.OnOperationStart(ctx, OperationInfo{Operation: "UpdateTags"})
	resp, err := c.gen.UpdateTagsWithResponse(ctx, body)
	if err != nil {
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "UpdateTags"}, OperationResult{Operation: "UpdateTags", Err: err})
		return nil, err
	}
	if resp.StatusCode() >= 400 {
		perr := parseError(resp.Body, resp.StatusCode(), resp.HTTPResponse)
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "UpdateTags"}, OperationResult{Operation: "UpdateTags", Err: perr})
		return nil, perr
	}
	c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "UpdateTags"}, OperationResult{Operation: "UpdateTags"})
	return resp, nil
}

// ShowStatement runs the show_statement operation (GET /statements/{id}).
func (c *Client) ShowStatement(ctx context.Context, id int) (*ShowStatementResponse, error) {
	ctx = c.hooks.OnOperationStart(ctx, OperationInfo{Operation: "ShowStatement"})
	resp, err := c.gen.ShowStatementWithResponse(ctx, id)
	if err != nil {
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "ShowStatement"}, OperationResult{Operation: "ShowStatement", Err: err})
		return nil, err
	}
	if resp.StatusCode() >= 400 {
		perr := parseError(resp.Body, resp.StatusCode(), resp.HTTPResponse)
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "ShowStatement"}, OperationResult{Operation: "ShowStatement", Err: perr})
		return nil, perr
	}
	c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "ShowStatement"}, OperationResult{Operation: "ShowStatement"})
	return resp, nil
}

// ListTeam runs the list_team operation (GET /team/members).
func (c *Client) ListTeam(ctx context.Context) (*ListTeamResponse, error) {
	ctx = c.hooks.OnOperationStart(ctx, OperationInfo{Operation: "ListTeam"})
	resp, err := c.gen.ListTeamWithResponse(ctx)
	if err != nil {
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "ListTeam"}, OperationResult{Operation: "ListTeam", Err: err})
		return nil, err
	}
	if resp.StatusCode() >= 400 {
		perr := parseError(resp.Body, resp.StatusCode(), resp.HTTPResponse)
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "ListTeam"}, OperationResult{Operation: "ListTeam", Err: perr})
		return nil, perr
	}
	c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "ListTeam"}, OperationResult{Operation: "ListTeam"})
	return resp, nil
}

// ListVehicleTags runs the list_vehicle_tags operation (GET /vehicle_tags).
func (c *Client) ListVehicleTags(ctx context.Context) (*ListVehicleTagsResponse, error) {
	ctx = c.hooks.OnOperationStart(ctx, OperationInfo{Operation: "ListVehicleTags"})
	resp, err := c.gen.ListVehicleTagsWithResponse(ctx)
	if err != nil {
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "ListVehicleTags"}, OperationResult{Operation: "ListVehicleTags", Err: err})
		return nil, err
	}
	if resp.StatusCode() >= 400 {
		perr := parseError(resp.Body, resp.StatusCode(), resp.HTTPResponse)
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "ListVehicleTags"}, OperationResult{Operation: "ListVehicleTags", Err: perr})
		return nil, perr
	}
	c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "ListVehicleTags"}, OperationResult{Operation: "ListVehicleTags"})
	return resp, nil
}

// CreateVehicleTag runs the create_vehicle_tag operation (POST /vehicle_tags).
func (c *Client) CreateVehicleTag(ctx context.Context, body CreateVehicleTagRequest) (*CreateVehicleTagResponse, error) {
	ctx = c.hooks.OnOperationStart(ctx, OperationInfo{Operation: "CreateVehicleTag"})
	resp, err := c.gen.CreateVehicleTagWithResponse(ctx, body)
	if err != nil {
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "CreateVehicleTag"}, OperationResult{Operation: "CreateVehicleTag", Err: err})
		return nil, err
	}
	if resp.StatusCode() >= 400 {
		perr := parseError(resp.Body, resp.StatusCode(), resp.HTTPResponse)
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "CreateVehicleTag"}, OperationResult{Operation: "CreateVehicleTag", Err: perr})
		return nil, perr
	}
	c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "CreateVehicleTag"}, OperationResult{Operation: "CreateVehicleTag"})
	return resp, nil
}

// DeleteVehicleTag runs the delete_vehicle_tag operation (DELETE /vehicle_tags/{id}).
func (c *Client) DeleteVehicleTag(ctx context.Context, id int) (*DeleteVehicleTagResponse, error) {
	ctx = c.hooks.OnOperationStart(ctx, OperationInfo{Operation: "DeleteVehicleTag"})
	resp, err := c.gen.DeleteVehicleTagWithResponse(ctx, id)
	if err != nil {
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "DeleteVehicleTag"}, OperationResult{Operation: "DeleteVehicleTag", Err: err})
		return nil, err
	}
	if resp.StatusCode() >= 400 {
		perr := parseError(resp.Body, resp.StatusCode(), resp.HTTPResponse)
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "DeleteVehicleTag"}, OperationResult{Operation: "DeleteVehicleTag", Err: perr})
		return nil, perr
	}
	c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "DeleteVehicleTag"}, OperationResult{Operation: "DeleteVehicleTag"})
	return resp, nil
}

// UpdateVehicleTag runs the update_vehicle_tag operation (PATCH /vehicle_tags/{id}).
func (c *Client) UpdateVehicleTag(ctx context.Context, id int, body UpdateVehicleTagRequest) (*UpdateVehicleTagResponse, error) {
	ctx = c.hooks.OnOperationStart(ctx, OperationInfo{Operation: "UpdateVehicleTag"})
	resp, err := c.gen.UpdateVehicleTagWithResponse(ctx, id, body)
	if err != nil {
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "UpdateVehicleTag"}, OperationResult{Operation: "UpdateVehicleTag", Err: err})
		return nil, err
	}
	if resp.StatusCode() >= 400 {
		perr := parseError(resp.Body, resp.StatusCode(), resp.HTTPResponse)
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "UpdateVehicleTag"}, OperationResult{Operation: "UpdateVehicleTag", Err: perr})
		return nil, perr
	}
	c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "UpdateVehicleTag"}, OperationResult{Operation: "UpdateVehicleTag"})
	return resp, nil
}

// ListVehicles runs the list_vehicles operation (GET /vehicles).
func (c *Client) ListVehicles(ctx context.Context, params *ListVehiclesParams) (*ListVehiclesResponse, error) {
	ctx = c.hooks.OnOperationStart(ctx, OperationInfo{Operation: "ListVehicles"})
	resp, err := c.gen.ListVehiclesWithResponse(ctx, params)
	if err != nil {
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "ListVehicles"}, OperationResult{Operation: "ListVehicles", Err: err})
		return nil, err
	}
	if resp.StatusCode() >= 400 {
		perr := parseError(resp.Body, resp.StatusCode(), resp.HTTPResponse)
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "ListVehicles"}, OperationResult{Operation: "ListVehicles", Err: perr})
		return nil, perr
	}
	c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "ListVehicles"}, OperationResult{Operation: "ListVehicles"})
	return resp, nil
}

// CreateVehicle runs the create_vehicle operation (POST /vehicles).
func (c *Client) CreateVehicle(ctx context.Context, body CreateVehicleRequest) (*CreateVehicleResponse, error) {
	ctx = c.hooks.OnOperationStart(ctx, OperationInfo{Operation: "CreateVehicle"})
	resp, err := c.gen.CreateVehicleWithResponse(ctx, body)
	if err != nil {
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "CreateVehicle"}, OperationResult{Operation: "CreateVehicle", Err: err})
		return nil, err
	}
	if resp.StatusCode() >= 400 {
		perr := parseError(resp.Body, resp.StatusCode(), resp.HTTPResponse)
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "CreateVehicle"}, OperationResult{Operation: "CreateVehicle", Err: perr})
		return nil, perr
	}
	c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "CreateVehicle"}, OperationResult{Operation: "CreateVehicle"})
	return resp, nil
}

// CheckVehicleDuplicate runs the check_vehicle_duplicate operation (GET /vehicles/check_duplicate).
func (c *Client) CheckVehicleDuplicate(ctx context.Context, params *CheckVehicleDuplicateParams) (*CheckVehicleDuplicateResponse, error) {
	ctx = c.hooks.OnOperationStart(ctx, OperationInfo{Operation: "CheckVehicleDuplicate"})
	resp, err := c.gen.CheckVehicleDuplicateWithResponse(ctx, params)
	if err != nil {
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "CheckVehicleDuplicate"}, OperationResult{Operation: "CheckVehicleDuplicate", Err: err})
		return nil, err
	}
	if resp.StatusCode() >= 400 {
		perr := parseError(resp.Body, resp.StatusCode(), resp.HTTPResponse)
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "CheckVehicleDuplicate"}, OperationResult{Operation: "CheckVehicleDuplicate", Err: perr})
		return nil, perr
	}
	c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "CheckVehicleDuplicate"}, OperationResult{Operation: "CheckVehicleDuplicate"})
	return resp, nil
}

// LookupVehicle runs the lookup_vehicle operation (GET /vehicles/lookup).
func (c *Client) LookupVehicle(ctx context.Context, params *LookupVehicleParams) (*LookupVehicleResponse, error) {
	ctx = c.hooks.OnOperationStart(ctx, OperationInfo{Operation: "LookupVehicle"})
	resp, err := c.gen.LookupVehicleWithResponse(ctx, params)
	if err != nil {
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "LookupVehicle"}, OperationResult{Operation: "LookupVehicle", Err: err})
		return nil, err
	}
	if resp.StatusCode() >= 400 {
		perr := parseError(resp.Body, resp.StatusCode(), resp.HTTPResponse)
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "LookupVehicle"}, OperationResult{Operation: "LookupVehicle", Err: perr})
		return nil, perr
	}
	c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "LookupVehicle"}, OperationResult{Operation: "LookupVehicle"})
	return resp, nil
}

// PrefillVehicle runs the prefill_vehicle operation (GET /vehicles/prefill).
func (c *Client) PrefillVehicle(ctx context.Context, params *PrefillVehicleParams) (*PrefillVehicleResponse, error) {
	ctx = c.hooks.OnOperationStart(ctx, OperationInfo{Operation: "PrefillVehicle"})
	resp, err := c.gen.PrefillVehicleWithResponse(ctx, params)
	if err != nil {
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "PrefillVehicle"}, OperationResult{Operation: "PrefillVehicle", Err: err})
		return nil, err
	}
	if resp.StatusCode() >= 400 {
		perr := parseError(resp.Body, resp.StatusCode(), resp.HTTPResponse)
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "PrefillVehicle"}, OperationResult{Operation: "PrefillVehicle", Err: perr})
		return nil, perr
	}
	c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "PrefillVehicle"}, OperationResult{Operation: "PrefillVehicle"})
	return resp, nil
}

// DecodeVin runs the decode_vin operation (GET /vehicles/vin_decode).
func (c *Client) DecodeVin(ctx context.Context, params *DecodeVinParams) (*DecodeVinResponse, error) {
	ctx = c.hooks.OnOperationStart(ctx, OperationInfo{Operation: "DecodeVin"})
	resp, err := c.gen.DecodeVinWithResponse(ctx, params)
	if err != nil {
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "DecodeVin"}, OperationResult{Operation: "DecodeVin", Err: err})
		return nil, err
	}
	if resp.StatusCode() >= 400 {
		perr := parseError(resp.Body, resp.StatusCode(), resp.HTTPResponse)
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "DecodeVin"}, OperationResult{Operation: "DecodeVin", Err: perr})
		return nil, perr
	}
	c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "DecodeVin"}, OperationResult{Operation: "DecodeVin"})
	return resp, nil
}

// DeleteVehicle runs the delete_vehicle operation (DELETE /vehicles/{id}).
func (c *Client) DeleteVehicle(ctx context.Context, id int) (*DeleteVehicleResponse, error) {
	ctx = c.hooks.OnOperationStart(ctx, OperationInfo{Operation: "DeleteVehicle"})
	resp, err := c.gen.DeleteVehicleWithResponse(ctx, id)
	if err != nil {
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "DeleteVehicle"}, OperationResult{Operation: "DeleteVehicle", Err: err})
		return nil, err
	}
	if resp.StatusCode() >= 400 {
		perr := parseError(resp.Body, resp.StatusCode(), resp.HTTPResponse)
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "DeleteVehicle"}, OperationResult{Operation: "DeleteVehicle", Err: perr})
		return nil, perr
	}
	c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "DeleteVehicle"}, OperationResult{Operation: "DeleteVehicle"})
	return resp, nil
}

// ShowVehicle runs the show_vehicle operation (GET /vehicles/{id}).
func (c *Client) ShowVehicle(ctx context.Context, id int) (*ShowVehicleResponse, error) {
	ctx = c.hooks.OnOperationStart(ctx, OperationInfo{Operation: "ShowVehicle"})
	resp, err := c.gen.ShowVehicleWithResponse(ctx, id)
	if err != nil {
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "ShowVehicle"}, OperationResult{Operation: "ShowVehicle", Err: err})
		return nil, err
	}
	if resp.StatusCode() >= 400 {
		perr := parseError(resp.Body, resp.StatusCode(), resp.HTTPResponse)
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "ShowVehicle"}, OperationResult{Operation: "ShowVehicle", Err: perr})
		return nil, perr
	}
	c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "ShowVehicle"}, OperationResult{Operation: "ShowVehicle"})
	return resp, nil
}

// UpdateVehicle runs the update_vehicle operation (PATCH /vehicles/{id}).
func (c *Client) UpdateVehicle(ctx context.Context, id int, body UpdateVehicleRequest) (*UpdateVehicleResponse, error) {
	ctx = c.hooks.OnOperationStart(ctx, OperationInfo{Operation: "UpdateVehicle"})
	resp, err := c.gen.UpdateVehicleWithResponse(ctx, id, body)
	if err != nil {
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "UpdateVehicle"}, OperationResult{Operation: "UpdateVehicle", Err: err})
		return nil, err
	}
	if resp.StatusCode() >= 400 {
		perr := parseError(resp.Body, resp.StatusCode(), resp.HTTPResponse)
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "UpdateVehicle"}, OperationResult{Operation: "UpdateVehicle", Err: perr})
		return nil, perr
	}
	c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "UpdateVehicle"}, OperationResult{Operation: "UpdateVehicle"})
	return resp, nil
}

// MergeVehicle runs the merge_vehicle operation (POST /vehicles/{id}/merge).
func (c *Client) MergeVehicle(ctx context.Context, id int, body MergeVehicleRequest) (*MergeVehicleResponse, error) {
	ctx = c.hooks.OnOperationStart(ctx, OperationInfo{Operation: "MergeVehicle"})
	resp, err := c.gen.MergeVehicleWithResponse(ctx, id, body)
	if err != nil {
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "MergeVehicle"}, OperationResult{Operation: "MergeVehicle", Err: err})
		return nil, err
	}
	if resp.StatusCode() >= 400 {
		perr := parseError(resp.Body, resp.StatusCode(), resp.HTTPResponse)
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "MergeVehicle"}, OperationResult{Operation: "MergeVehicle", Err: perr})
		return nil, perr
	}
	c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "MergeVehicle"}, OperationResult{Operation: "MergeVehicle"})
	return resp, nil
}

// TransferVehicle runs the transfer_vehicle operation (PATCH /vehicles/{id}/transfer).
func (c *Client) TransferVehicle(ctx context.Context, id int, body TransferVehicleRequest) (*TransferVehicleResponse, error) {
	ctx = c.hooks.OnOperationStart(ctx, OperationInfo{Operation: "TransferVehicle"})
	resp, err := c.gen.TransferVehicleWithResponse(ctx, id, body)
	if err != nil {
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "TransferVehicle"}, OperationResult{Operation: "TransferVehicle", Err: err})
		return nil, err
	}
	if resp.StatusCode() >= 400 {
		perr := parseError(resp.Body, resp.StatusCode(), resp.HTTPResponse)
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "TransferVehicle"}, OperationResult{Operation: "TransferVehicle", Err: perr})
		return nil, perr
	}
	c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "TransferVehicle"}, OperationResult{Operation: "TransferVehicle"})
	return resp, nil
}

// ListVehiclesWorkOrders runs the list_vehicles_work_orders operation (GET /vehicles/{vehicle_id}/work_orders).
func (c *Client) ListVehiclesWorkOrders(ctx context.Context, vehicleId int) (*ListVehiclesWorkOrdersResponse, error) {
	ctx = c.hooks.OnOperationStart(ctx, OperationInfo{Operation: "ListVehiclesWorkOrders"})
	resp, err := c.gen.ListVehiclesWorkOrdersWithResponse(ctx, vehicleId)
	if err != nil {
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "ListVehiclesWorkOrders"}, OperationResult{Operation: "ListVehiclesWorkOrders", Err: err})
		return nil, err
	}
	if resp.StatusCode() >= 400 {
		perr := parseError(resp.Body, resp.StatusCode(), resp.HTTPResponse)
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "ListVehiclesWorkOrders"}, OperationResult{Operation: "ListVehiclesWorkOrders", Err: perr})
		return nil, perr
	}
	c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "ListVehiclesWorkOrders"}, OperationResult{Operation: "ListVehiclesWorkOrders"})
	return resp, nil
}

// ListVendors runs the list_vendors operation (GET /vendors).
func (c *Client) ListVendors(ctx context.Context) (*ListVendorsResponse, error) {
	ctx = c.hooks.OnOperationStart(ctx, OperationInfo{Operation: "ListVendors"})
	resp, err := c.gen.ListVendorsWithResponse(ctx)
	if err != nil {
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "ListVendors"}, OperationResult{Operation: "ListVendors", Err: err})
		return nil, err
	}
	if resp.StatusCode() >= 400 {
		perr := parseError(resp.Body, resp.StatusCode(), resp.HTTPResponse)
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "ListVendors"}, OperationResult{Operation: "ListVendors", Err: perr})
		return nil, perr
	}
	c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "ListVendors"}, OperationResult{Operation: "ListVendors"})
	return resp, nil
}

// ShowVendor runs the show_vendor operation (GET /vendors/{id}).
func (c *Client) ShowVendor(ctx context.Context, id int) (*ShowVendorResponse, error) {
	ctx = c.hooks.OnOperationStart(ctx, OperationInfo{Operation: "ShowVendor"})
	resp, err := c.gen.ShowVendorWithResponse(ctx, id)
	if err != nil {
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "ShowVendor"}, OperationResult{Operation: "ShowVendor", Err: err})
		return nil, err
	}
	if resp.StatusCode() >= 400 {
		perr := parseError(resp.Body, resp.StatusCode(), resp.HTTPResponse)
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "ShowVendor"}, OperationResult{Operation: "ShowVendor", Err: perr})
		return nil, perr
	}
	c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "ShowVendor"}, OperationResult{Operation: "ShowVendor"})
	return resp, nil
}

// ListWorkOrders runs the list_work_orders operation (GET /work_orders).
func (c *Client) ListWorkOrders(ctx context.Context) (*ListWorkOrdersResponse, error) {
	ctx = c.hooks.OnOperationStart(ctx, OperationInfo{Operation: "ListWorkOrders"})
	resp, err := c.gen.ListWorkOrdersWithResponse(ctx)
	if err != nil {
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "ListWorkOrders"}, OperationResult{Operation: "ListWorkOrders", Err: err})
		return nil, err
	}
	if resp.StatusCode() >= 400 {
		perr := parseError(resp.Body, resp.StatusCode(), resp.HTTPResponse)
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "ListWorkOrders"}, OperationResult{Operation: "ListWorkOrders", Err: perr})
		return nil, perr
	}
	c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "ListWorkOrders"}, OperationResult{Operation: "ListWorkOrders"})
	return resp, nil
}

// CreateWorkOrder runs the create_work_order operation (POST /work_orders).
func (c *Client) CreateWorkOrder(ctx context.Context, body CreateWorkOrderRequest) (*CreateWorkOrderResponse, error) {
	ctx = c.hooks.OnOperationStart(ctx, OperationInfo{Operation: "CreateWorkOrder"})
	resp, err := c.gen.CreateWorkOrderWithResponse(ctx, body)
	if err != nil {
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "CreateWorkOrder"}, OperationResult{Operation: "CreateWorkOrder", Err: err})
		return nil, err
	}
	if resp.StatusCode() >= 400 {
		perr := parseError(resp.Body, resp.StatusCode(), resp.HTTPResponse)
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "CreateWorkOrder"}, OperationResult{Operation: "CreateWorkOrder", Err: perr})
		return nil, perr
	}
	c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "CreateWorkOrder"}, OperationResult{Operation: "CreateWorkOrder"})
	return resp, nil
}

// DeleteWorkOrder runs the delete_work_order operation (DELETE /work_orders/{id}).
func (c *Client) DeleteWorkOrder(ctx context.Context, id int) (*DeleteWorkOrderResponse, error) {
	ctx = c.hooks.OnOperationStart(ctx, OperationInfo{Operation: "DeleteWorkOrder"})
	resp, err := c.gen.DeleteWorkOrderWithResponse(ctx, id)
	if err != nil {
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "DeleteWorkOrder"}, OperationResult{Operation: "DeleteWorkOrder", Err: err})
		return nil, err
	}
	if resp.StatusCode() >= 400 {
		perr := parseError(resp.Body, resp.StatusCode(), resp.HTTPResponse)
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "DeleteWorkOrder"}, OperationResult{Operation: "DeleteWorkOrder", Err: perr})
		return nil, perr
	}
	c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "DeleteWorkOrder"}, OperationResult{Operation: "DeleteWorkOrder"})
	return resp, nil
}

// ShowWorkOrder runs the show_work_order operation (GET /work_orders/{id}).
func (c *Client) ShowWorkOrder(ctx context.Context, id int) (*ShowWorkOrderResponse, error) {
	ctx = c.hooks.OnOperationStart(ctx, OperationInfo{Operation: "ShowWorkOrder"})
	resp, err := c.gen.ShowWorkOrderWithResponse(ctx, id)
	if err != nil {
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "ShowWorkOrder"}, OperationResult{Operation: "ShowWorkOrder", Err: err})
		return nil, err
	}
	if resp.StatusCode() >= 400 {
		perr := parseError(resp.Body, resp.StatusCode(), resp.HTTPResponse)
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "ShowWorkOrder"}, OperationResult{Operation: "ShowWorkOrder", Err: perr})
		return nil, perr
	}
	c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "ShowWorkOrder"}, OperationResult{Operation: "ShowWorkOrder"})
	return resp, nil
}

// UpdateWorkOrder runs the update_work_order operation (PATCH /work_orders/{id}).
func (c *Client) UpdateWorkOrder(ctx context.Context, id int, body UpdateWorkOrderRequest) (*UpdateWorkOrderResponse, error) {
	ctx = c.hooks.OnOperationStart(ctx, OperationInfo{Operation: "UpdateWorkOrder"})
	resp, err := c.gen.UpdateWorkOrderWithResponse(ctx, id, body)
	if err != nil {
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "UpdateWorkOrder"}, OperationResult{Operation: "UpdateWorkOrder", Err: err})
		return nil, err
	}
	if resp.StatusCode() >= 400 {
		perr := parseError(resp.Body, resp.StatusCode(), resp.HTTPResponse)
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "UpdateWorkOrder"}, OperationResult{Operation: "UpdateWorkOrder", Err: perr})
		return nil, perr
	}
	c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "UpdateWorkOrder"}, OperationResult{Operation: "UpdateWorkOrder"})
	return resp, nil
}

// ShowWorkOrderDeclinedServices runs the show_work_order_declined_services operation (GET /work_orders/{work_order_id}/declined_services).
func (c *Client) ShowWorkOrderDeclinedServices(ctx context.Context, workOrderId int) (*ShowWorkOrderDeclinedServicesResponse, error) {
	ctx = c.hooks.OnOperationStart(ctx, OperationInfo{Operation: "ShowWorkOrderDeclinedServices"})
	resp, err := c.gen.ShowWorkOrderDeclinedServicesWithResponse(ctx, workOrderId)
	if err != nil {
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "ShowWorkOrderDeclinedServices"}, OperationResult{Operation: "ShowWorkOrderDeclinedServices", Err: err})
		return nil, err
	}
	if resp.StatusCode() >= 400 {
		perr := parseError(resp.Body, resp.StatusCode(), resp.HTTPResponse)
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "ShowWorkOrderDeclinedServices"}, OperationResult{Operation: "ShowWorkOrderDeclinedServices", Err: perr})
		return nil, perr
	}
	c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "ShowWorkOrderDeclinedServices"}, OperationResult{Operation: "ShowWorkOrderDeclinedServices"})
	return resp, nil
}

// ShowWorkOrderServiceHistory runs the show_work_order_service_history operation (GET /work_orders/{work_order_id}/service_history).
func (c *Client) ShowWorkOrderServiceHistory(ctx context.Context, workOrderId int) (*ShowWorkOrderServiceHistoryResponse, error) {
	ctx = c.hooks.OnOperationStart(ctx, OperationInfo{Operation: "ShowWorkOrderServiceHistory"})
	resp, err := c.gen.ShowWorkOrderServiceHistoryWithResponse(ctx, workOrderId)
	if err != nil {
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "ShowWorkOrderServiceHistory"}, OperationResult{Operation: "ShowWorkOrderServiceHistory", Err: err})
		return nil, err
	}
	if resp.StatusCode() >= 400 {
		perr := parseError(resp.Body, resp.StatusCode(), resp.HTTPResponse)
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "ShowWorkOrderServiceHistory"}, OperationResult{Operation: "ShowWorkOrderServiceHistory", Err: perr})
		return nil, perr
	}
	c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "ShowWorkOrderServiceHistory"}, OperationResult{Operation: "ShowWorkOrderServiceHistory"})
	return resp, nil
}

// CreateWorkOrderAuthorization runs the create_work_order_authorization operation (POST /work_orders/{work_order_id}/authorization).
func (c *Client) CreateWorkOrderAuthorization(ctx context.Context, workOrderId int, body CreateWorkOrderAuthorizationRequest) (*CreateWorkOrderAuthorizationResponse, error) {
	ctx = c.hooks.OnOperationStart(ctx, OperationInfo{Operation: "CreateWorkOrderAuthorization"})
	resp, err := c.gen.CreateWorkOrderAuthorizationWithResponse(ctx, workOrderId, body)
	if err != nil {
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "CreateWorkOrderAuthorization"}, OperationResult{Operation: "CreateWorkOrderAuthorization", Err: err})
		return nil, err
	}
	if resp.StatusCode() >= 400 {
		perr := parseError(resp.Body, resp.StatusCode(), resp.HTTPResponse)
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "CreateWorkOrderAuthorization"}, OperationResult{Operation: "CreateWorkOrderAuthorization", Err: perr})
		return nil, perr
	}
	c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "CreateWorkOrderAuthorization"}, OperationResult{Operation: "CreateWorkOrderAuthorization"})
	return resp, nil
}

// UpdateWorkOrderAuthorizationDecisions runs the update_work_order_authorization_decisions operation (POST /work_orders/{work_order_id}/authorization/update_decisions).
func (c *Client) UpdateWorkOrderAuthorizationDecisions(ctx context.Context, workOrderId int, body UpdateWorkOrderAuthorizationDecisionsRequest) (*UpdateWorkOrderAuthorizationDecisionsResponse, error) {
	ctx = c.hooks.OnOperationStart(ctx, OperationInfo{Operation: "UpdateWorkOrderAuthorizationDecisions"})
	resp, err := c.gen.UpdateWorkOrderAuthorizationDecisionsWithResponse(ctx, workOrderId, body)
	if err != nil {
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "UpdateWorkOrderAuthorizationDecisions"}, OperationResult{Operation: "UpdateWorkOrderAuthorizationDecisions", Err: err})
		return nil, err
	}
	if resp.StatusCode() >= 400 {
		perr := parseError(resp.Body, resp.StatusCode(), resp.HTTPResponse)
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "UpdateWorkOrderAuthorizationDecisions"}, OperationResult{Operation: "UpdateWorkOrderAuthorizationDecisions", Err: perr})
		return nil, perr
	}
	c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "UpdateWorkOrderAuthorizationDecisions"}, OperationResult{Operation: "UpdateWorkOrderAuthorizationDecisions"})
	return resp, nil
}

// ShowWorkOrderEstimate runs the show_work_order_estimate operation (GET /work_orders/{work_order_id}/estimate).
func (c *Client) ShowWorkOrderEstimate(ctx context.Context, workOrderId int) (*ShowWorkOrderEstimateResponse, error) {
	ctx = c.hooks.OnOperationStart(ctx, OperationInfo{Operation: "ShowWorkOrderEstimate"})
	resp, err := c.gen.ShowWorkOrderEstimateWithResponse(ctx, workOrderId)
	if err != nil {
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "ShowWorkOrderEstimate"}, OperationResult{Operation: "ShowWorkOrderEstimate", Err: err})
		return nil, err
	}
	if resp.StatusCode() >= 400 {
		perr := parseError(resp.Body, resp.StatusCode(), resp.HTTPResponse)
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "ShowWorkOrderEstimate"}, OperationResult{Operation: "ShowWorkOrderEstimate", Err: perr})
		return nil, perr
	}
	c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "ShowWorkOrderEstimate"}, OperationResult{Operation: "ShowWorkOrderEstimate"})
	return resp, nil
}

// ShowWorkOrderInspection runs the show_work_order_inspection operation (GET /work_orders/{work_order_id}/inspection).
func (c *Client) ShowWorkOrderInspection(ctx context.Context, workOrderId int) (*ShowWorkOrderInspectionResponse, error) {
	ctx = c.hooks.OnOperationStart(ctx, OperationInfo{Operation: "ShowWorkOrderInspection"})
	resp, err := c.gen.ShowWorkOrderInspectionWithResponse(ctx, workOrderId)
	if err != nil {
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "ShowWorkOrderInspection"}, OperationResult{Operation: "ShowWorkOrderInspection", Err: err})
		return nil, err
	}
	if resp.StatusCode() >= 400 {
		perr := parseError(resp.Body, resp.StatusCode(), resp.HTTPResponse)
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "ShowWorkOrderInspection"}, OperationResult{Operation: "ShowWorkOrderInspection", Err: perr})
		return nil, perr
	}
	c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "ShowWorkOrderInspection"}, OperationResult{Operation: "ShowWorkOrderInspection"})
	return resp, nil
}

// CloseWorkOrder runs the close_work_order operation (PATCH /work_orders/{work_order_id}/lifecycle/close).
func (c *Client) CloseWorkOrder(ctx context.Context, workOrderId int, body CloseWorkOrderRequest) (*CloseWorkOrderResponse, error) {
	ctx = c.hooks.OnOperationStart(ctx, OperationInfo{Operation: "CloseWorkOrder"})
	resp, err := c.gen.CloseWorkOrderWithResponse(ctx, workOrderId, body)
	if err != nil {
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "CloseWorkOrder"}, OperationResult{Operation: "CloseWorkOrder", Err: err})
		return nil, err
	}
	if resp.StatusCode() >= 400 {
		perr := parseError(resp.Body, resp.StatusCode(), resp.HTTPResponse)
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "CloseWorkOrder"}, OperationResult{Operation: "CloseWorkOrder", Err: perr})
		return nil, perr
	}
	c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "CloseWorkOrder"}, OperationResult{Operation: "CloseWorkOrder"})
	return resp, nil
}

// CloseWorkOrderAsPaid runs the close_work_order_as_paid operation (PATCH /work_orders/{work_order_id}/lifecycle/close_as_paid).
func (c *Client) CloseWorkOrderAsPaid(ctx context.Context, workOrderId int, body CloseWorkOrderAsPaidRequest) (*CloseWorkOrderAsPaidResponse, error) {
	ctx = c.hooks.OnOperationStart(ctx, OperationInfo{Operation: "CloseWorkOrderAsPaid"})
	resp, err := c.gen.CloseWorkOrderAsPaidWithResponse(ctx, workOrderId, body)
	if err != nil {
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "CloseWorkOrderAsPaid"}, OperationResult{Operation: "CloseWorkOrderAsPaid", Err: err})
		return nil, err
	}
	if resp.StatusCode() >= 400 {
		perr := parseError(resp.Body, resp.StatusCode(), resp.HTTPResponse)
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "CloseWorkOrderAsPaid"}, OperationResult{Operation: "CloseWorkOrderAsPaid", Err: perr})
		return nil, perr
	}
	c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "CloseWorkOrderAsPaid"}, OperationResult{Operation: "CloseWorkOrderAsPaid"})
	return resp, nil
}

// DeclineAllWorkOrderServices runs the decline_all_work_order_services operation (PATCH /work_orders/{work_order_id}/lifecycle/decline_all).
func (c *Client) DeclineAllWorkOrderServices(ctx context.Context, workOrderId int, body DeclineAllWorkOrderServicesRequest) (*DeclineAllWorkOrderServicesResponse, error) {
	ctx = c.hooks.OnOperationStart(ctx, OperationInfo{Operation: "DeclineAllWorkOrderServices"})
	resp, err := c.gen.DeclineAllWorkOrderServicesWithResponse(ctx, workOrderId, body)
	if err != nil {
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "DeclineAllWorkOrderServices"}, OperationResult{Operation: "DeclineAllWorkOrderServices", Err: err})
		return nil, err
	}
	if resp.StatusCode() >= 400 {
		perr := parseError(resp.Body, resp.StatusCode(), resp.HTTPResponse)
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "DeclineAllWorkOrderServices"}, OperationResult{Operation: "DeclineAllWorkOrderServices", Err: perr})
		return nil, perr
	}
	c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "DeclineAllWorkOrderServices"}, OperationResult{Operation: "DeclineAllWorkOrderServices"})
	return resp, nil
}

// ReopenWorkOrder runs the reopen_work_order operation (PATCH /work_orders/{work_order_id}/lifecycle/reopen).
func (c *Client) ReopenWorkOrder(ctx context.Context, workOrderId int, body ReopenWorkOrderRequest) (*ReopenWorkOrderResponse, error) {
	ctx = c.hooks.OnOperationStart(ctx, OperationInfo{Operation: "ReopenWorkOrder"})
	resp, err := c.gen.ReopenWorkOrderWithResponse(ctx, workOrderId, body)
	if err != nil {
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "ReopenWorkOrder"}, OperationResult{Operation: "ReopenWorkOrder", Err: err})
		return nil, err
	}
	if resp.StatusCode() >= 400 {
		perr := parseError(resp.Body, resp.StatusCode(), resp.HTTPResponse)
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "ReopenWorkOrder"}, OperationResult{Operation: "ReopenWorkOrder", Err: perr})
		return nil, perr
	}
	c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "ReopenWorkOrder"}, OperationResult{Operation: "ReopenWorkOrder"})
	return resp, nil
}

// ReturnWorkOrderToBoard runs the return_work_order_to_board operation (PATCH /work_orders/{work_order_id}/lifecycle/return_to_board).
func (c *Client) ReturnWorkOrderToBoard(ctx context.Context, workOrderId int, body ReturnWorkOrderToBoardRequest) (*ReturnWorkOrderToBoardResponse, error) {
	ctx = c.hooks.OnOperationStart(ctx, OperationInfo{Operation: "ReturnWorkOrderToBoard"})
	resp, err := c.gen.ReturnWorkOrderToBoardWithResponse(ctx, workOrderId, body)
	if err != nil {
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "ReturnWorkOrderToBoard"}, OperationResult{Operation: "ReturnWorkOrderToBoard", Err: err})
		return nil, err
	}
	if resp.StatusCode() >= 400 {
		perr := parseError(resp.Body, resp.StatusCode(), resp.HTTPResponse)
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "ReturnWorkOrderToBoard"}, OperationResult{Operation: "ReturnWorkOrderToBoard", Err: perr})
		return nil, perr
	}
	c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "ReturnWorkOrderToBoard"}, OperationResult{Operation: "ReturnWorkOrderToBoard"})
	return resp, nil
}

// SaveWorkOrderForLater runs the save_work_order_for_later operation (PATCH /work_orders/{work_order_id}/lifecycle/save_for_later).
func (c *Client) SaveWorkOrderForLater(ctx context.Context, workOrderId int, body SaveWorkOrderForLaterRequest) (*SaveWorkOrderForLaterResponse, error) {
	ctx = c.hooks.OnOperationStart(ctx, OperationInfo{Operation: "SaveWorkOrderForLater"})
	resp, err := c.gen.SaveWorkOrderForLaterWithResponse(ctx, workOrderId, body)
	if err != nil {
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "SaveWorkOrderForLater"}, OperationResult{Operation: "SaveWorkOrderForLater", Err: err})
		return nil, err
	}
	if resp.StatusCode() >= 400 {
		perr := parseError(resp.Body, resp.StatusCode(), resp.HTTPResponse)
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "SaveWorkOrderForLater"}, OperationResult{Operation: "SaveWorkOrderForLater", Err: perr})
		return nil, perr
	}
	c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "SaveWorkOrderForLater"}, OperationResult{Operation: "SaveWorkOrderForLater"})
	return resp, nil
}

// StageTransitionWorkOrder runs the stage_transition_work_order operation (PATCH /work_orders/{work_order_id}/lifecycle/stage_transition).
func (c *Client) StageTransitionWorkOrder(ctx context.Context, workOrderId int, body StageTransitionWorkOrderRequest) (*StageTransitionWorkOrderResponse, error) {
	ctx = c.hooks.OnOperationStart(ctx, OperationInfo{Operation: "StageTransitionWorkOrder"})
	resp, err := c.gen.StageTransitionWorkOrderWithResponse(ctx, workOrderId, body)
	if err != nil {
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "StageTransitionWorkOrder"}, OperationResult{Operation: "StageTransitionWorkOrder", Err: err})
		return nil, err
	}
	if resp.StatusCode() >= 400 {
		perr := parseError(resp.Body, resp.StatusCode(), resp.HTTPResponse)
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "StageTransitionWorkOrder"}, OperationResult{Operation: "StageTransitionWorkOrder", Err: perr})
		return nil, perr
	}
	c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "StageTransitionWorkOrder"}, OperationResult{Operation: "StageTransitionWorkOrder"})
	return resp, nil
}

// ShowWorkOrderParts runs the show_work_order_parts operation (GET /work_orders/{work_order_id}/parts).
func (c *Client) ShowWorkOrderParts(ctx context.Context, workOrderId int) (*ShowWorkOrderPartsResponse, error) {
	ctx = c.hooks.OnOperationStart(ctx, OperationInfo{Operation: "ShowWorkOrderParts"})
	resp, err := c.gen.ShowWorkOrderPartsWithResponse(ctx, workOrderId)
	if err != nil {
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "ShowWorkOrderParts"}, OperationResult{Operation: "ShowWorkOrderParts", Err: err})
		return nil, err
	}
	if resp.StatusCode() >= 400 {
		perr := parseError(resp.Body, resp.StatusCode(), resp.HTTPResponse)
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "ShowWorkOrderParts"}, OperationResult{Operation: "ShowWorkOrderParts", Err: perr})
		return nil, perr
	}
	c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "ShowWorkOrderParts"}, OperationResult{Operation: "ShowWorkOrderParts"})
	return resp, nil
}

// ShowWorkOrderPayments runs the show_work_order_payments operation (GET /work_orders/{work_order_id}/payments).
func (c *Client) ShowWorkOrderPayments(ctx context.Context, workOrderId int) (*ShowWorkOrderPaymentsResponse, error) {
	ctx = c.hooks.OnOperationStart(ctx, OperationInfo{Operation: "ShowWorkOrderPayments"})
	resp, err := c.gen.ShowWorkOrderPaymentsWithResponse(ctx, workOrderId)
	if err != nil {
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "ShowWorkOrderPayments"}, OperationResult{Operation: "ShowWorkOrderPayments", Err: err})
		return nil, err
	}
	if resp.StatusCode() >= 400 {
		perr := parseError(resp.Body, resp.StatusCode(), resp.HTTPResponse)
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "ShowWorkOrderPayments"}, OperationResult{Operation: "ShowWorkOrderPayments", Err: perr})
		return nil, perr
	}
	c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "ShowWorkOrderPayments"}, OperationResult{Operation: "ShowWorkOrderPayments"})
	return resp, nil
}

// CreateWorkOrderPayment runs the create_work_order_payment operation (POST /work_orders/{work_order_id}/payments).
func (c *Client) CreateWorkOrderPayment(ctx context.Context, workOrderId int, body CreateWorkOrderPaymentRequest) (*CreateWorkOrderPaymentResponse, error) {
	ctx = c.hooks.OnOperationStart(ctx, OperationInfo{Operation: "CreateWorkOrderPayment"})
	resp, err := c.gen.CreateWorkOrderPaymentWithResponse(ctx, workOrderId, body)
	if err != nil {
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "CreateWorkOrderPayment"}, OperationResult{Operation: "CreateWorkOrderPayment", Err: err})
		return nil, err
	}
	if resp.StatusCode() >= 400 {
		perr := parseError(resp.Body, resp.StatusCode(), resp.HTTPResponse)
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "CreateWorkOrderPayment"}, OperationResult{Operation: "CreateWorkOrderPayment", Err: perr})
		return nil, perr
	}
	c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "CreateWorkOrderPayment"}, OperationResult{Operation: "CreateWorkOrderPayment"})
	return resp, nil
}

// ShowWorkOrderWip runs the show_work_order_wip operation (GET /work_orders/{work_order_id}/wip).
func (c *Client) ShowWorkOrderWip(ctx context.Context, workOrderId int) (*ShowWorkOrderWipResponse, error) {
	ctx = c.hooks.OnOperationStart(ctx, OperationInfo{Operation: "ShowWorkOrderWip"})
	resp, err := c.gen.ShowWorkOrderWipWithResponse(ctx, workOrderId)
	if err != nil {
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "ShowWorkOrderWip"}, OperationResult{Operation: "ShowWorkOrderWip", Err: err})
		return nil, err
	}
	if resp.StatusCode() >= 400 {
		perr := parseError(resp.Body, resp.StatusCode(), resp.HTTPResponse)
		c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "ShowWorkOrderWip"}, OperationResult{Operation: "ShowWorkOrderWip", Err: perr})
		return nil, perr
	}
	c.hooks.OnOperationEnd(ctx, OperationInfo{Operation: "ShowWorkOrderWip"}, OperationResult{Operation: "ShowWorkOrderWip"})
	return resp, nil
}






// GetAllCustomers auto-paginates list_customers, following the Link header up to
// 1000 items by default.
func (c *Client) GetAllCustomers(ctx context.Context, params *ListCustomersParams) ([]Customer, error) {
	first, err := c.ListCustomers(ctx, params)
	if err != nil {
		return nil, err
	}
	return collectAll[Customer](ctx, c, first.Body, first.HTTPResponse.Header.Get("Link"), 1000)
}



// GetAllLookupCustomer auto-paginates lookup_customer, following the Link header up to
// 1000 items by default.
func (c *Client) GetAllLookupCustomer(ctx context.Context, params *LookupCustomerParams) ([]Customer, error) {
	first, err := c.LookupCustomer(ctx, params)
	if err != nil {
		return nil, err
	}
	return collectAll[Customer](ctx, c, first.Body, first.HTTPResponse.Header.Get("Link"), 1000)
}

// GetAllCustomersDrivers auto-paginates list_customers_drivers, following the Link header up to
// 1000 items by default.
func (c *Client) GetAllCustomersDrivers(ctx context.Context, customerId int) ([]Driver, error) {
	first, err := c.ListCustomersDrivers(ctx, customerId)
	if err != nil {
		return nil, err
	}
	return collectAll[Driver](ctx, c, first.Body, first.HTTPResponse.Header.Get("Link"), 1000)
}





// GetAllCustomersStatements auto-paginates list_customers_statements, following the Link header up to
// 1000 items by default.
func (c *Client) GetAllCustomersStatements(ctx context.Context, customerId int) ([]Statement, error) {
	first, err := c.ListCustomersStatements(ctx, customerId)
	if err != nil {
		return nil, err
	}
	return collectAll[Statement](ctx, c, first.Body, first.HTTPResponse.Header.Get("Link"), 1000)
}

// GetAllCustomersVehicles auto-paginates list_customers_vehicles, following the Link header up to
// 1000 items by default.
func (c *Client) GetAllCustomersVehicles(ctx context.Context, customerId int) ([]Vehicle, error) {
	first, err := c.ListCustomersVehicles(ctx, customerId)
	if err != nil {
		return nil, err
	}
	return collectAll[Vehicle](ctx, c, first.Body, first.HTTPResponse.Header.Get("Link"), 1000)
}


// GetAllCustomersWorkOrders auto-paginates list_customers_work_orders, following the Link header up to
// 1000 items by default.
func (c *Client) GetAllCustomersWorkOrders(ctx context.Context, customerId int) ([]WorkOrder, error) {
	first, err := c.ListCustomersWorkOrders(ctx, customerId)
	if err != nil {
		return nil, err
	}
	return collectAll[WorkOrder](ctx, c, first.Body, first.HTTPResponse.Header.Get("Link"), 1000)
}






// GetAllServiceCategories auto-paginates list_service_categories, following the Link header up to
// 1000 items by default.
func (c *Client) GetAllServiceCategories(ctx context.Context) ([]ServiceCategory, error) {
	first, err := c.ListServiceCategories(ctx)
	if err != nil {
		return nil, err
	}
	return collectAll[ServiceCategory](ctx, c, first.Body, first.HTTPResponse.Header.Get("Link"), 1000)
}

















// GetAllVehicles auto-paginates list_vehicles, following the Link header up to
// 1000 items by default.
func (c *Client) GetAllVehicles(ctx context.Context, params *ListVehiclesParams) ([]Vehicle, error) {
	first, err := c.ListVehicles(ctx, params)
	if err != nil {
		return nil, err
	}
	return collectAll[Vehicle](ctx, c, first.Body, first.HTTPResponse.Header.Get("Link"), 1000)
}



// GetAllLookupVehicle auto-paginates lookup_vehicle, following the Link header up to
// 1000 items by default.
func (c *Client) GetAllLookupVehicle(ctx context.Context, params *LookupVehicleParams) ([]Vehicle, error) {
	first, err := c.LookupVehicle(ctx, params)
	if err != nil {
		return nil, err
	}
	return collectAll[Vehicle](ctx, c, first.Body, first.HTTPResponse.Header.Get("Link"), 1000)
}








// GetAllVehiclesWorkOrders auto-paginates list_vehicles_work_orders, following the Link header up to
// 1000 items by default.
func (c *Client) GetAllVehiclesWorkOrders(ctx context.Context, vehicleId int) ([]WorkOrder, error) {
	first, err := c.ListVehiclesWorkOrders(ctx, vehicleId)
	if err != nil {
		return nil, err
	}
	return collectAll[WorkOrder](ctx, c, first.Body, first.HTTPResponse.Header.Get("Link"), 1000)
}

// GetAllVendors auto-paginates list_vendors, following the Link header up to
// 1000 items by default.
func (c *Client) GetAllVendors(ctx context.Context) ([]Vendor, error) {
	first, err := c.ListVendors(ctx)
	if err != nil {
		return nil, err
	}
	return collectAll[Vendor](ctx, c, first.Body, first.HTTPResponse.Header.Get("Link"), 1000)
}


// GetAllWorkOrders auto-paginates list_work_orders, following the Link header up to
// 1000 items by default.
func (c *Client) GetAllWorkOrders(ctx context.Context) ([]WorkOrder, error) {
	first, err := c.ListWorkOrders(ctx)
	if err != nil {
		return nil, err
	}
	return collectAll[WorkOrder](ctx, c, first.Body, first.HTTPResponse.Header.Get("Link"), 1000)
}





















